### ISSUE TITLE
Warning / error / exception should be thrown when tld list can't be fetched or when it is empty

### ISSUE THREAD

**Issue by dav009** [john-kurkowski/tldextract#100]
I was using `tldextract` 1.4 and it was silently failing to download the list of tlds.
failing silently is an easy way to shoot oneself in the foot.

It would be great to get some sort of warning/exception when this happens i.e:
-  warning if it is not a fresh instalation (terhe is a tld already tho outdated)
- exception if hte list of tlds is empty
- ship a default list of TLDs? and try to update it on the first run?

**Comment by john-kurkowski** [comment]
Definitely it should scream about failing to get any TLDs. It should also
try backup URLs.

1.4 is quite old. Is this fixed in 2.0.1?

**Comment by dav009** [comment]
yes, things work alright from 1.7.5 upwards.

@john-kurkowski I've been using mostly the old version.
a few questions:

- is the new version shipping with a default set of TLDs?  this would be good, since it would assure functionality in various trivial cases ( if the list fails to download tldextract goes wrong on very simple cases i.e: `http://abcd.co` )

Happy to make a PR if we define a way to handle this

**Comment by dav009** [comment]
Actually the newest version seems to already influcde a default list of tlds

**Comment by john-kurkowski** [comment]
What you describe is what it does, I think! [This docstring](https://github.com/john-kurkowski/tldextract/blob/2.0.1/tldextract/tldextract.py#L114-L126) describes the default on-first-run and fallback steps. You can also pass options to override these steps.

**Comment by dav009** [comment]
👍  yeah, new version address the issues I posted, thanks
