### ISSUE TITLE
Solution for when Effective TLD Names endpoint is down

### ISSUE THREAD

**Issue by mihai-tiriplica-hs** [john-kurkowski/tldextract#101]
Hello Mozilla's tld names endpoint has been down for two days:
http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1 and tldextract does not work

Is there a workaround or a way to use other tld names services?

**Comment by john-kurkowski** [comment]
mxr.mozilla.org? This project hasn't used that URL in a long time. I just did a clean install of tldextract 2.0.1 and the PSL downloaded fine. Can you try a newer version of tldextract?

> Is there a workaround or a way to use other tld names services?

For the record, yes. You can pass alternative URLs when you construct a `TLDExtract` instance. See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/2.0.1#specifying-your-own-url-or-file-for-the-suffix-list-data).

**Comment by mihai-tiriplica-hs** [comment]
Sorry, I haven't notice mxr.mozilla is not used in the newer versions. I will try an upgrade. Thank you!
