### ISSUE TITLE
Bug when extracting 'www.nhs.uk'

### ISSUE THREAD

**Issue by akatsukle** [john-kurkowski/tldextract#102]
2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>>> import tldextract
\>>> tldextract.extract('http://www.nhs.uk')
ExtractResult(subdomain='', domain='www', suffix='nhs.uk')
\>>> tldextract.extract('www.nhs.uk')
ExtractResult(subdomain='', domain='www', suffix='nhs.uk')
\>>> tldextract.\__version\__
'2.0.1'

I don't really know what is causing this, if you can't reproduce, I would be happy to give more configuration information.

**Comment by john-kurkowski** [comment]
That is a correct extraction. It is its own suffix [according to the PSL](https://github.com/publicsuffix/list/blob/274e07a82611bede81f8af2f475abc0bb97790fb/public_suffix_list.dat#L6179).

**Comment by akatsukle** [comment]
Oh right. Then shouldn't the subdomain still be www whithout domain?
If we try to join them with '.' then we get an unexpected result.
\>>> ext = tldextract.extract('http://www.nhs.uk')
\>>> ".".join(ext[:3])
'.www.nhs.uk'

**Comment by john-kurkowski** [comment]
The subdomain and suffix of tldextract's namedtuple are optional. Not all domain name-like strings have a subdomain, or a valid suffix. If you want to rejoin the whole thing, regardless of whether a subdomain or suffix was found, try

```python
>>> '.'.join(part for part in ext if part)
'www.nhs.uk'
```

I'd consider baking in an alias for this. Nobody's ever asked before, but seems simple enough to maintain.

**Comment by akatsukle** [comment]
Thanks, your join is probably the way to go. 
I was surprised because in the documentation it's not specified, and the join inside the docs made me believe it was the way to go.

**Comment by john-kurkowski** [comment]
I could add this discussion to the README at least.

**Comment by john-kurkowski** [comment]
Added.

**Comment by wumpus** [comment]
Thank you for this documentation improvement, it saved me some trouble!
