### ISSUE TITLE
domain extracted wrongly

### ISSUE THREAD

**Issue by mayajohn** [john-kurkowski/tldextract#103]
for the url "http://static.ibnlive.in.com/ibnlive/pix/ibnhome/cricketnext/microsite/teamsicon/ind.png.
the result for tldextract is 
ExtractResult(subdomain='static.ibnlive', domain='in', suffix='com')

**Comment by john-kurkowski** [comment]
That looks correct to me. What do you expect?

**Comment by mayajohn** [comment]
Is not ibnlive the domain?  i guess 'in' refers to country information india.

**Comment by john-kurkowski** [comment]
Nope, [the PSL doesn't mention in.com](https://github.com/publicsuffix/list/blob/b0e37a2da9a795baf3bc1aee1c5a58fd98ab8e9f/public_suffix_list.dat). It's its own registered domain, not a suffix. Today at least.
