### ISSUE TITLE
uk.com private tld is not parsed as expected

### ISSUE THREAD

**Issue by wavenator** [john-kurkowski/tldextract#105]
`In [4]: tldextract.extract('test.uk.com')`
`Out[4]: ExtractResult(subdomain='test', domain='uk', suffix='com')`

**Comment by hangtwenty** [comment]
Are you using the latest suffix list or no? That may be correct according to [the snapshot here](https://raw.githubusercontent.com/john-kurkowski/tldextract/master/tldextract/.tld_set_snapshot), but maybe not according to [latest public suffix list](https://publicsuffix.org/list/public_suffix_list.dat). (Try grepping for 'com' and 'uk.com' on each and notice the former does not have any entry for 'uk.com', though the latter does.)

See also these sections in the README:
* https://github.com/john-kurkowski/tldextract#note-about-caching
* https://github.com/john-kurkowski/tldextract#advanced-usage

If something still seems off to you, please re-open and add details about what you've tried. Thanks!

**Comment by john-kurkowski** [comment]
I looked closer at the title of the PR.

> _private_ tld is not parsed 

As of writing, uk.com is indeed [mentioned in the PSL as a _private_ domain](https://github.com/publicsuffix/list/blob/b4a941a2df2eeaf5e2380311ee6b5e24e2125764/public_suffix_list.dat#L10766). If you want tldextract to include private domains as suffixes, see the `include_psl_private_domains` option when constructing a `TLDExtract`.
