### ISSUE TITLE
GAE compatibility

### ISSUE THREAD

**Issue by thomasf1** [john-kurkowski/tldextract#106]
I´m having trouble using tldextract on app engine. I´m not quite sure how you did it, maybe it was a earlier Version that did allow reading files...

Currently I´m getting a "IOError: [Errno 13] file not accessible" - the same error as this guy: http://stackoverflow.com/questions/28006949/how-to-use-tldextract-in-google-app-engine

**Comment by hangtwenty** [comment]
Check out the GAE app in this very repository: https://github.com/john-kurkowski/tldextract/tree/master/tldextract_app

**Comment by john-kurkowski** [comment]
The tldextract_app folder worked at one point, **but** I haven't used GAE in years. I doubt I've updated the deployed app in that time. _Something_ is still there, responding, but I don't know what it is!

Also the tldextract_app folder isn't doing anything special. It's a thin wrapper around tldextract and importing dependencies. No tldextract-specific magic.

Anyway, back to the OP. Unfortunately, I don't know what could be wrong

If it comes down to a code change, a PR to make tldextract more cloud-service friendly would be awesome!

In the meantime, I should probably remove specific mention of GAE from the repo. I don't maintain it. tldextract shouldn't be platform-specific either.

**Comment by thomasf1** [comment]
I´ve had trouble getting the gae example to work... Now I´ve modified tldextract to play nice with GAE. Unfortunately, it´s quite specific to GAE (Memcache)

**Comment by hangtwenty** [comment]
@thomasf1 curious, does your solution use [this method](https://cloud.google.com/appengine/docs/standard/python/googlecloudstorageclient/read-write-to-cloud-storage) or something else? since you mentioned memcached, wasn't sure

**Comment by hangtwenty** [comment]
@thomasf1 let us know if you are still interested in this. if so, can you open a PR with that change you made? it's ok for a _subclass_ of `TLDExtract` to have coupling to GAE etc., as long as any `import <optional stuff>` is deferred until that class's instantiation. make sense?

---------------------------------------------------------

else, @john-kurkowski could deprecate the `tldextract_app` directory, and delete the mention in the README

**Comment by hangtwenty** [comment]
Closing because old (and we had the "needs clarification" label on it for a while)
