### ISSUE TITLE
I'm a little confused with a particular domain

### ISSUE THREAD

**Issue by rustybrooks** [john-kurkowski/tldextract#109]
Someone pointed out to me that tldextract's behavior with a specific domain seemed odd.  The domain in question is "waw.pl", which it treats somewhat like if you passed in "co.uk", i.e. it is treated as a pure suffix.

> tldextract.extract('waw.pl')
> ExtractResult(subdomain='', domain='', suffix='waw.pl')

But I don't think this is true.  For example, www.waw.pl is a valid hostname/website.  But if I try it with tldextract I get

> tldextract.extract('www.waw.pl')
> ExtractResult(subdomain='', domain='www', suffix='waw.pl')

I don't know if this is an error in the data in tldextract, or an error in my understanding of how it should work.

**Comment by rustybrooks** [comment]
It occurs to me that *maybe* someone registered themselves "www" as a domain in waw.pl and tldextract is essentially correct.  Kind of a weird thing but I guess it could be?

**Comment by rustybrooks** [comment]
In fact it seems that someone has done this for co.uk - there is a www.co.uk, that's a domain mind you, not a hostname.  Oddly, they are not running a server at www.co.uk, you have to go to www.www.co.uk

**Comment by john-kurkowski** [comment]
Strange but true. "waw.pl" is a public suffix [according to the list](https://github.com/publicsuffix/list/blob/1a8f371fe7a6021ca5d845cb45644dd15a84d6c8/public_suffix_list.dat#L5542).

**Comment by rustybrooks** [comment]
Yeah, I came to this conclusion finally myself last night.  I had seen that it was on this list but I wasn't convinced.  But I managed to convince myself.  I was just so thrown by the existence of www.waw.pl.  I probably should have waited to write to you here.  Thanks for your response.
