### ISSUE TITLE
method that takes a netloc instead of an URL?

### ISSUE THREAD

**Issue by wumpus** [john-kurkowski/tldextract#111]
I have some code for which url parsing is performance-sensitive, and I'm trying to reduce the number of times the full url is parsed. I'm also hoping to have one urlparser so that there's no way any url would get parsed one way by one module and a different way by another.

tldextract currently only takes an url as an argument. If I already know the netloc, then it'd be nice to have a different function to extract from that. It wouldn't make the tldextract code too ugly.

Alternately, the existing code extract() happens to do the right thing, albeit with a little extra expense, for extract('example.com').  It is not documented or tested that this works. I am willing to bet that there are some users of your code mistakenly depending on this functionality!

What do you think should be done? You might say "nothing", that's fine. I'm willing to take a stab at implementing if you think something should be done.

**Comment by john-kurkowski** [comment]
> If I already know the netloc, then it'd be nice to have a different function to extract from that.

Sure, I think an alternate method wouldn't hurt.

Maybe split `__call__(self, url)` into 2 methods:

1. `extract_url(self, url)`: an alias for the existing `__call__`
2. `extract_netloc(self, netloc)`: your new netloc-only version, which can save a few operations

What do you think?

**Comment by john-kurkowski** [comment]
> Alternately, the existing code extract() happens to do the right thing, albeit with a little extra expense

I don't follow. How is it of help here?

```python
extract('example.com')
``` 

is just shorthand for 

```python
TLDExtract()('example.com')
```

**Comment by wumpus** [comment]
extract('example.com') is passing in an URL which lacks a scheme. I had thought that this was undocumented but I see that in fact you do have an example that works that way.  I thought you didn't test this scheme-less case, but looking more carefully at your test-cases I see that you do.

So, sorry, never mind. If I do run into a significant performance problem I'll open a new issue.

**Comment by john-kurkowski** [comment]
Gotcha. Yeah, it's pretty lenient with input. It doesn't require a strict URL.
