### ISSUE TITLE
Special character domains?

### ISSUE THREAD

**Issue by 011121** [john-kurkowski/tldextract#113]
There are four characters handled specially by IDN according to unicode.org:

> Q: Which four characters are interpreted differently?
> 
> A: Four characters can cause an IDNA2008 implementation to go to a different web page than an IDNA2003 implementation, given the same source, such as href="http://faß.de". These four characters include some that are quite common in languages such as German, Greek, Farsi, and Sinhala:
> 
> U+00DF ( ß ) LATIN SMALL LETTER SHARP S
> U+03C2 ( ς ) GREEK SMALL LETTER FINAL SIGMA
> U+200C ( ) ZERO WIDTH NON-JOINER
> U+200D ( ) ZERO WIDTH JOINER
> 
> For the purposes of discussion of differences between IDNA versions, these characters are called "deviations".
http://unicode.org/faq/idn.html

My understanding is that there are domain differences in the handling of these characters, at least in some cases.  For instance the sharp-s character only appears to be legal IDN for .de domains.  For anyone else it should be converted to 'ss.'

Should this functionality be included in tldextract?

i.e. right now `tldextract.extract('http://faß.de').domain` correctly gives `'faß'` but
`tldextract.extract('http://faß.au').domain` also gives `'faß'` when it probably should give `'fass'`

**Comment by john-kurkowski** [comment]
Whew, [that FAQ](http://unicode.org/faq/idn.html) is interesting but a doozy! If I were to summarize, a lot of the entries are of the form, "Q: Shouldn't ABC be simple? A: No, consider exception XYZ." 😏 Is there a clear-cut mapping and algorithm for unwinding these deviations? Maybe I missed it. To include the algorithm in tldextract, it depends on how complicated the algorithm is and how many input options it has to handle. Perhaps it belongs in another library.

**Comment by commutecat** [comment]
@john-kurkowski 
Python 2.7 and above already embedded IDNA encoding into the string. (Together with the caveat of Python 2 string as ascii vs python 3 string as unicode) .  This including various punycode(homoglphy) conversion  into the same idna encoding function. 
`Python3
>>> url = 'http://faß.de'
>>> url.encode('idna')
b'http://fass.de'

>>>punyurl = "http://ρaypal.com" 
>>>punyurl.encode('idna')
b'xn--http://aypal-v3i.com'
`
I just found out tldextract use the old import idna libraries, when diagnose an error throw by tldextract , which is due to problematic code of the old `import idna` . Although the issue mainly due to faillure to normalise the url

`
hostname = 'Natürlich!.com' 
tldextract.extract(hostanme.encode('idna')) 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/virtualenv/xxx/lib/python3.5/site-packages/tldextract/tldextract.py", line 329, in extract
    return TLD_EXTRACTOR(url)
  File "/home/user/virtualenv/xxx/lib/python3.5/site-packages/tldextract/tldextract.py", line 186, in __call__
    netloc = SCHEME_RE.sub("", url) \
TypeError: cannot use a string pattern on a bytes-like object

`

**Comment by john-kurkowski** [comment]
> Python 2.7 and above already embedded IDNA encoding into the string ... I just found out tldextract use the old import idna libraries, which is due old `import idna`

Actually [the idna package claims it is the newer one](https://github.com/kjd/idna/blame/v2.5/README.rst#L12-L14):

> This acts as a suitable replacement for the “encodings.idna” module that comes with the Python standard library, but only supports the old, deprecated IDNA specification ([`RFC 3490`](http://tools.ietf.org/html/rfc3490)).

**Comment by john-kurkowski** [comment]
> Python 2.7 and above already embedded IDNA encoding into the string ... I just found out tldextract use the old import idna libraries, which is due old `import idna`

Actually [the idna package claims it is the newer one](https://github.com/kjd/idna/blame/v2.5/README.rst#L12-L14):

> This acts as a suitable replacement for the “encodings.idna” module that comes with the Python standard library, but only supports the old, deprecated IDNA specification ([RFC 3490](http://tools.ietf.org/html/rfc3490)).

Relevant to the discussion here, the idna package [eschews mapping on purpose](https://github.com/kjd/idna/blame/v2.5/README.rst#L100-L104):

> As described in [RFC 5895](http://tools.ietf.org/html/rfc5895), the IDNA specification no longer normalizes input from different potential ways a user may input a domain name. This functionality, known as a “mapping”, is now considered by the specification to be a local user-interface issue distinct from IDNA conversion functionality.

**Comment by hangtwenty** [comment]
@011121  i've added the label `low priority: can be solved by pre/post processing`. if that's not the case, let me know and i'll remove that label.

also marked with `contributions welcome` -- while this is some interesting nuts-and-bolts stuff, and was definitely worth discussing ... most users do not need it, seemingly.

**Comment by john-kurkowski** [comment]
> … most users do not need it, seemingly.

Closing stale issue.
