### ISSUE TITLE
Import errors occur when used inside spark

### ISSUE THREAD

**Issue by ddvlamin** [john-kurkowski/tldextract#118]
The below script simply iterates over json objects which contain urls. From each of these urls we wish to extract the domain using tldextract 2.0.2. This is done within spark using pyspark 2.0.0 (running default standalone local mode) and a virtualenv using python2.7.6

```
import json

import pyspark

def map2domain(x):
  """
  x (dict): {"urls": [{"identifier":"https://www.amazon.com"},{"identifier":"http://www.google.com"}]}
  """
  import tldextract
  l = []
  for url in x["urls"]:
    l.append(tldextract.extract(url["identifier"]).domain)
  return l


if __name__ == "__main__":

  sc = pyspark.SparkContext(appName="TldInSparkTest")

  pid2segment = sc.textFile("/path/to/part-0000[0-3]").map(json.loads)
  print pid2segment.flatMap(map2domain).takeOrdered(5,key=lambda x: x)
  sc.stop()
```

However when executing this code import errors occur (see [errors](http://pastebin.com/NDi9BvBj)). As a consequence tasks fail and are retried. On a second retry of the task it then seems to succeed.

Each time it is executed it seems to be slightly different errors and different tasks that fail. Furthermore it succeeds without errors when I run the script on only 1 file, when I start giving more files to process, it starts to give the aforementioned errors.

Could anyone give an explanation as to why this happens and how to solve it? This does not happen with other packages such as tld. Which is why I assume it has something to do with tldextract specifics or not?

**Comment by john-kurkowski** [comment]
Something to do with that "context" (`SparkContext`)? Is that like the virtualenv it's run in? I notice the first error is in /home/ubuntu/spark/python/lib/pyspark.zip/pyspark/ but there are deeper calls to /home/ubuntu/predicube/pythonVirtualEnv/predicube_spark/local/lib/python2.7/site-packages/tldextract/. The former looks like a centralized Python install. The latter like a virtualenv. I don't know if Spark must be run that way. Personally, I've only had misery mixing centralized/virtualenv Python installations.

```
"/home/ubuntu/predicube/pythonVirtualEnv/predicube_spark/local/lib/python2.7/site-packages/tldextract/tldextract.py", line 78, in <module>
    from .remote import find_first_response
ImportError: No module named remote
```

Sounds like an incomplete install of the tldextract source. A file in in this project is missing. You say later runs pass? Was the install completed sometime between the 1st and later runs?

```
"/home/ubuntu/predicube/pythonVirtualEnv/predicube_spark/local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
ImportError: No module named compat
```

Again, a core part of a 3rd party library, [python-requests](http://docs.python-requests.org/en/master/), is missing here. Incomplete install? tldextract isn't doing any magic to bring that in. `pip install tldextract` should've brought in python-requests fully.

**Comment by ddvlamin** [comment]
Thanks for giving the question some attention, I wasn't sure whether this was the right place to ask (on stackoverflow no one seems to care or understand) because the error might be caused due to some conflicts/interplay between tldextract and spark.

What I mean with "later runs" is something specific to Spark. Spark will split the input data in parts and process them in parallel on multiple workers. Each of these parts are processed in tasks and when a task fails Spark will retry it. The weird thing is that when the task is retried (due to this previous mentioned tldextract issue) it seems to be successful. But I want to know where these errors come from so that I can trust the results that come out of it.

To submit the job to spark the pyspark lib /home/ubuntu/spark/python/lib/pyspark.zip/pyspark/  is used I guess. But in the configuration we explicitly set the virtual environment to be used by pyspark.

I'm not sure what you mean with a centralized python install? But given that we point pyspark to the virtual environment I assume it uses the virtual env. If I go into the pyspark shell I can import and use tldextract

I checked and these versions are installed in the virtual env:
requests==2.13.0
requests-file==1.4.1
tld==0.7.8
tldextract==2.0.2
urllib3==1.20
virtualenv==15.1.0

**Comment by john-kurkowski** [comment]
> Thanks for giving the question some attention, I'm not sure whether this is the right place to ask ... because the error might be caused due to some conflicts/interplay between tldextract and spark.

Doesn't hurt to ask! I'd like tldextract to be a straightforward Python package, able to run in parallel, not pulling any tricks. Unfortunately nothing comes to mind why it wouldn't run under Spark.

> To submit the job to spark the pyspark lib /home/ubuntu/spark/python/lib/pyspark.zip/pyspark/ is used I guess. But in the configuration we explicitly set the virtual environment to be used by pyspark.
>
> I'm not sure what you mean with a centralized python install?

For example, my OS ships with Python at /usr/bin/python. I can `easy_install` packages for its use. Virtualenv is not in play. I call this a centralized install of Python. I can separately install a Virtualenv, with its Python version at ~/.virtualenvs/some_virtualenv_name/bin/python. Using the Virtualenv, package installs will just exist for the Virtualenv. The 2 Python installs do not share packages. If you're not careful setting up your `PATH` though, you may encounter strange or misleading `ImportError`s, where you're not using the Python you think you're using.

Is Spark typically meant to be used this way, you launch it from one place, and give it a foreknown Virtualenv in another place? Is the Virtualenv already set up? Does Spark set it up? Does some devops tool set it up?

> If I go into the pyspark shell I can import and use tldextract

Is this after the failures?

**Comment by alekhyapuranam** [comment]
iam working on spyder and iam executing the below code
import os
import sys
import re
import matplotlib
import pandas as pd
import numpy as np
from os.path import splitext
import ipaddress as ip
import tldextract
import whois
import datetime
from urllib.parse import urlparse

and iam getting the below error 
No module named 'tldextract'

could any one please help me to solve this problem

**Comment by edsu** [comment]
I'm not sure if this helps at all, but I ran across the same error, and noticed commenting the import of requests on [lines 9-10](https://github.com/john-kurkowski/tldextract/blob/master/tldextract/remote.py#L9-L10) in tldextract.remote allowed me to import tldextract in my Spark task. Of course it's not usable in that state, but I thought it was interesting that import requests is what triggered the broken pipe error from pyspark.

**Comment by edsu** [comment]
This is kind of an off the wall Idea but I wonder if it could be related to the way tldextract's cache works when there are multiple processes loading tldextract at the same time?

**Comment by john-kurkowski** [comment]
I revisited the OP pastebin. I already noted the difference in Python paths. Some of the errors further down the logs are due to upstream import errors, like in python-requests. I'm thinking this is an environment issue. Not something this library can help with. As for the cache concurrency idea, sure, I'll wait to close this until #144 or #146, which introduce a lock.
