### ISSUE TITLE
Issue with in.net and jp.net suffixed domains

### ISSUE THREAD

**Issue by 011121** [john-kurkowski/tldextract#119]
When using tldextract on jp.net or in.net suffixed domains the result returns only the net for the suffix and the prior portion for the domain:

>>> import tldextract
>>> tldextract.extract('abc123.jp.net')
ExtractResult(subdomain='abc123', domain='jp', suffix='net')

Shouldn't the suffix be jp.net and the domain be abc123 in this example?

**Comment by john-kurkowski** [comment]
Note the position of jp.net and in.net in [the latest PSL](https://github.com/publicsuffix/list/blob/6efe629f1ae212f6d8a1dffd3ddf999c3c597b36/public_suffix_list.dat#L10629). The PSL categorizes them categorizes as _private_ domains. If you want tldextract to treat them as public, see [this section of the README](https://github.com/john-kurkowski/tldextract/blob/5962abe7ad2340abbeece17e2d41003f8b6980d8/README.md#public-vs-private-domains).

**Comment by 011121** [comment]
Ah, beautiful.  Sorry for the confusion!
