### ISSUE TITLE
docs: improve PyPi description and long_description

### ISSUE THREAD

**Issue by jvanasco** [john-kurkowski/tldextract#121]
The PyPi description currently reads:

> Accurately separate the TLD from the registered domain and subdomains of a URL, using the Public Suffix List.

This makes no mention of the package's ability to ignore private domains.  

Same thing with the long_description https://github.com/john-kurkowski/tldextract/blob/master/setup.py#L1-L22

I've passed over this library a few dozen times because I know what the Public Suffix list is, and needed to avoid treating the private domains as if they were public.  It wasn't until a friend told me "take a deeper look, it can differentiate between public and private".

**Comment by john-kurkowski** [comment]
I was afraid to overwhelm the PSL newcomer. But sure, 1 additional, brief sentence wouldn't hurt!

**Comment by jvanasco** [comment]
I just thinking of something short like "This package supports ICANN TLDs with an option to include private domains from the Public Suffix List.

**Comment by john-kurkowski** [comment]
Closed via #125.
