### ISSUE TITLE
python 2.7 is often 'narrow', doesn't catch unicode error

### ISSUE THREAD

**Issue by jvanasco** [john-kurkowski/tldextract#122]
this example will work on python3.x but breaks on many default python2.7 installs (including many OSX and Ubuntu):

    import tldextract
    tldextract.extract('xn--vi8hiv.ws')

it will raise:

    ValueError: unichr() arg not in range(0x10000) (narrow Python build)

The problem is in that this block only checks for a `UnicodeError`:  https://github.com/john-kurkowski/tldextract/blob/2.0.2/tldextract/tldextract.py#L198-L204

however if Python wasn't compiled with support for 'wide' unicode, this will raise a `ValueError`

there are many strategies for supporting 'narrow' unicode, or this could just be caught and skipped.

**Comment by john-kurkowski** [comment]
> there are many strategies for supporting 'narrow' unicode, or this could just be caught and skipped.

I'm fine with "caught and skipped." Though I'm curious what the strategies and their tradeoffs are.

**Comment by jvanasco** [comment]
the two most popular methods on stackoverflow/github/maillinglists I've found are:

use unicode-escape to store as a utf16 pair
* http://stackoverflow.com/questions/7105874/valueerror-unichr-arg-not-in-range0x10000-narrow-python-build-please-hel

rebuild it using struct
* https://github.com/euske/pdfminer/pull/148/commits/cea7eefde6301e377bb4a3a499fb2e2ace8c2a78

I saw a few other approaches.  I haven't had time to dig into them yet.

I've had lots of issues with unicode over the years, but it's been a long time since the last one.  this one surprised me!

**Comment by john-kurkowski** [comment]
Whew, that's not bad. I was dreading new 3rd party packages or files.

**Comment by jvanasco** [comment]
Adding for reference: PEP 261 - support for wide characters

https://www.python.org/dev/peps/pep-0261/

**Comment by hangtwenty** [comment]
It's 2020 and Python 2.x is dead.
