### ISSUE TITLE
Invalid parsing for news.google.com.ru

### ISSUE THREAD

**Issue by yurii-cliqz** [john-kurkowski/tldextract#123]
```python
>>> import tldextract
>>> tldextract.__version__
2.0.2
>>> tldextract.extract('https://news.google.com.ru')
ExtractResult(subdomain='news.google', domain='com', suffix='ru')
```

Suppose to be:

```python
ExtractResult(subdomain='news', domain='google', suffix='com.ru')
```

**Comment by john-kurkowski** [comment]
Note the domain's position in [the latest PSL](https://github.com/publicsuffix/list/blob/cabeda8651aa3ca353cecca9c6bc8ad77cd04751/public_suffix_list.dat#L11215). The PSL categorizes the domain as _private_. If you want tldextract to treat private domains as public, see [this section of the README](https://github.com/john-kurkowski/tldextract/blob/5962abe7ad2340abbeece17e2d41003f8b6980d8/README.md#public-vs-private-domains).

**Comment by yurii-cliqz** [comment]
got it, thank you for your fast reply
