### ISSUE TITLE
parsing issue for tricky website 

### ISSUE THREAD

**Issue by MindtreeAnalytics** [john-kurkowski/tldextract#127]
Hi,
When in try to parse the URL "http://bullseye.in.com/tv/" and get the domain from it.
Tdlextract gives me **in** as a domain but actually it should be **bullseye**.

**Comment by john-kurkowski** [comment]
I don't see in.com mentioned as a public suffix anywhere in [the PSL](https://github.com/publicsuffix/list/blob/cabeda8651aa3ca353cecca9c6bc8ad77cd04751/public_suffix_list.dat), or in that repo's history. If you think it should be, submit a PR there.
