### ISSUE TITLE
.onion not recognized as a valid suffix

### ISSUE THREAD

**Issue by lopuhin** [john-kurkowski/tldextract#131]
I'm not sure it's in scope for ``tldextact``, but I expected that ``.onion`` domains would be recognized in a similar way to ``.com`` domains, but currently behavior is different:
```
>>> tldextract.extract('http://foo.onion').registered_domain
''
>>> tldextract.extract('http://foo.onion')
ExtractResult(subdomain='foo', domain='onion', suffix='')

>>> tldextract.extract('http://foo.com')
ExtractResult(subdomain='', domain='foo', suffix='com')
```

**Comment by john-kurkowski** [comment]
The suffixes are controlled by the Public Suffix List, not this repo. It did [add `.onion`](https://github.com/publicsuffix/list/pull/386) several months ago. Have you [updated tldextract's cache](https://github.com/john-kurkowski/tldextract/tree/2.1.0#note-about-caching)?

**Comment by lopuhin** [comment]
Oh right, indeed I had an older version, it works as expected with an updated cache.
Thanks a lot for the library and for a prompt response!
