### ISSUE TITLE
Inconsistent handling of malformed(?) URLs with successive dots

### ISSUE THREAD

**Issue by srenfo** [john-kurkowski/tldextract#134]
I'm not sure if this should be caught by tldextract or if it's fine as is. Feel free to close.

It doesn't make much sense to me to return non-empty subdomains and suffix but an empty domain:
```
>>> tldextract.extract('example.com')
ExtractResult(subdomain='', domain='example', suffix='com')
>>> tldextract.extract('example..com')
ExtractResult(subdomain='example', domain='', suffix='com')
>>> tldextract.extract('example...com')
ExtractResult(subdomain='example.', domain='', suffix='com')
>>> tldextract.extract('example....com')
ExtractResult(subdomain='example..', domain='', suffix='com')
```
On the other hand this is what the user passed in, so... I don't know.

At minimum this breaks the 'rejoin the whole namedtuple' example from the README. One of the dots is swallowed.

```
>>> ext = tldextract.extract('example..com')
>>> '.'.join(part for part in ext if part)
'example.com'
```

**Comment by john-kurkowski** [comment]
Agreed, those are non-sensical `ExtractResult`s. What could be a better signal to the user the input was bogus? Short of becoming a URL validator.

**Comment by hangtwenty** [comment]
Closing because old
