### ISSUE TITLE
Support .bit TLD

### ISSUE THREAD

**Issue by Heat-Miser** [john-kurkowski/tldextract#135]
Hello

It looks like TLDExtract does not support .bit TLD (https://en.wikipedia.org/wiki/.bit)

Do you think it's possible to add it ?

Thanks a lot.

Regards

**Comment by john-kurkowski** [comment]
This project doesn't contain an actual list of public suffixes. That comes from [the Public Suffix List](https://publicsuffix.org/). Can you submit an amendment there?

(The Wikipedia article makes the suffix sound _different_, controversial. I wonder if they'll take it.)

**Comment by Heat-Miser** [comment]
Thanks for your prompt feedback ! I've just submit an issue on their side !
Will see.

**Comment by Heat-Miser** [comment]
Well they said "nope" :)

https://github.com/publicsuffix/list/issues/505

**Comment by john-kurkowski** [comment]
:(

If it's important for your tldextract to treat this as a public suffix, you can either

* Fork the PSL and set the link in the [`suffix_list_urls`](https://github.com/john-kurkowski/tldextract/blob/2.1.0/tldextract/tldextract.py#L173) option
* Add your suffix piecemeal with [`additional_suffixes`](https://github.com/john-kurkowski/tldextract/blob/eb99c9b3fbaa3690d6e68dc480cd69aae9c21c1a/tldextract/tldextract.py#L191) option

**Comment by richtier** [comment]
note the additional suffixes is actually set with `extra_suffixes`. The docs also refer to `additional_suffixes `. I've made a PR to rectify this:

https://github.com/john-kurkowski/tldextract/pull/143
