### ISSUE TITLE
Benin gtld suport (.bj)

### ISSUE THREAD

**Issue by hellysmile** [john-kurkowski/tldextract#136]
Hey, right now `tldexract` can not get registered_domain from `http://gouv.bj/ ` This domain is really exists and owned by Benin government

**Comment by john-kurkowski** [comment]
This project doesn't contain an actual list of public suffixes. That comes from [the Public Suffix List](https://publicsuffix.org/). Can you submit an amendment there?

**Comment by john-kurkowski** [comment]
I've added [a FAQ entry](https://github.com/john-kurkowski/tldextract/blob/5ba3aa0252b4f512492b87376f2687be4b36d422/README.md#faq) for these requests, with some workarounds.
