### ISSUE TITLE
Incorrect results for `de.com` domains

### ISSUE THREAD

**Issue by sammacbeth** [john-kurkowski/tldextract#142]
`tldextract` seems to be giving incorrect results for `de.com` domains. Its results are inconsistant with the [tld](https://pypi.python.org/pypi/tld) python library, and [tldjs](https://github.com/oncletom/tld.js) in Javascript.

Given a url `http://www.nachrichten.de.com`, we expect the `registered_domain` to be `nachrichten.de.com`, as `de.com` is in the Public Suffix List. However, using tldextract `2.2.0` I get the following:

```python
import tldextract
tldextract.extract('http://www.nachrichten.de.com').registered_domain
>> 'de.com'
```

The tld library currently resolves this domain correctly:
```python
import tld
tld.get_tld('http://www.nachrichten.de.com')
>> u'nachrichten.de.com'
```

Likewise tldjs gets the same result:
```javascript
tldjs.parse('http://www.nachrichten.de.com').domain
>> "nachrichten.de.com"
```

**Comment by john-kurkowski** [comment]
See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/2.2.0#public-vs-private-domains). de.com is in the private section of [the PSL](https://github.com/publicsuffix/list/blob/85fa8fbdf73a0f2fcf5f4790c204394557dfbaf3/public_suffix_list.dat#L10768).

**Comment by Aronabv** [comment]
Have the same issue with: "https://online.ddc.uk.net". It recognized "uk" as the domain

**Comment by john-kurkowski** [comment]
Same solution as my previous comment. This is the default behavior by design. You can toggle it.

**Comment by john-kurkowski** [comment]
I don't think there's a bug here. Ping me back if I'm missing something.

**Comment by sammacbeth** [comment]
Thanks for the clarification. Perhaps a note in the readme that this default behaviour differs to the mentioned libraries would help prevent others thinking that this is a bug in future?

**Comment by john-kurkowski** [comment]
Good suggestion. Added. Thoughts?

**Comment by sammacbeth** [comment]
Looks good. Thanks for clarifying this.
