### ISSUE TITLE
co.ua not present in .tld_set_snapshot

### ISSUE THREAD

**Issue by shahsparx** [john-kurkowski/tldextract#147]
Because of this issue, 'https://ukrbotj.co.ua/' returns domain as co and suffix as ua

**Comment by ugarg1994** [comment]
Also .um domain is not present.

**Comment by abiralS** [comment]
com.de and co.ua is present as suffix in https://publicsuffix.org/list/public_suffix_list.dat but not treated as suffix by tldextract.

**Comment by hangtwenty** [comment]
when you need a TLD that is not in the snapshot, we encourage you to use the library's support for controlling your own cache file. you can do that at global level or per `TLDExtract` instance.

see:

* https://github.com/john-kurkowski/tldextract#note-about-caching 
* https://github.com/john-kurkowski/tldextract#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____
