### ISSUE TITLE
Feature Request: Change the location of the local cache to the users home directory.

### ISSUE THREAD

**Issue by draperjames** [john-kurkowski/tldextract#149]
Running tldextract 2.2.0 on Python 3.6.5 on Windows 10.

Currently when I run:
`
tldextract.extract("https://example.com")
`
It runs just fine but I get the following error:
`unable to cache TLDs in file C:\Program Files\Miniconda3\lib\site-packages\tldextract\.tld_set: [Errno 13] Permission denied: 'C:\\Program Files\\Miniconda3\\lib\\site-packages\\tldextract\\.tld_set'
`
There are multiple ways to approach this but I believe the best is writing the cache somewhere in the users home directory. Similar to the way IPython and Matplotlib do it. That way the user wouldn't have to change the permissions of the specific site package.

**Comment by draperjames** [comment]
PR #146 fixes this issue.

**Comment by hangtwenty** [comment]
@draperjames it's trivial to tell tldextract where to save the cache, actually!

* first option: you can set the environment variable, `TLDEXTRACT_CACHE`. this will affect the singleton instance that you are using in your example above. https://github.com/john-kurkowski/tldextract/blob/master/tldextract/tldextract.py#L94 
* second: instantiate your own `TLDExtract`. it takes keyword arguments and one of these is `cache_file` https://github.com/john-kurkowski/tldextract/blob/master/tldextract/tldextract.py#L162

**Comment by hangtwenty** [comment]
regarding option2, this kinda relates to #146 

you could have each thread have its own namespacing of a cache file. you could either use the thread ID or (probably better).

that opens a way you would be able to address #146, without having to couple  the default behavior to `threading ... and even if you are using `threading` then no lock is needed you could have each thread namespace the file and

**Comment by hangtwenty** [comment]
sorry for the noise, fat fingered some things

**Comment by hangtwenty** [comment]
oh right this is covered in the docs - so we won't need to update docs in relation to this issue

https://github.com/john-kurkowski/tldextract#specifying-your-own-url-or-file-for-the-suffix-list-data

**Comment by hangtwenty** [comment]
Lastly: hey, it's understandable that you'd want the defaults, with no arguments, to behave that way, plenty of things default to `$HOME`. however there are also other cases where people want to control their own permissions about HOME vs other things. the current behavior seems to be sane for the vast majority of users, so for now this does not need to change. just set `TLDEXTRACT_CACHE` as you please 🙂

**Comment by john-kurkowski** [comment]
Related: #9

**Comment by john-kurkowski** [comment]
Arguably came up again: #196
