### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by flock3** [john-kurkowski/tldextract#156]
Hi!
It looks like TLDExtract does not support IPv6 (IPv4 works fine):

```
In [5]:  tldextract.extract('http://[2001:0db8:85a3:08d3::0370:7344]:8080/')
Out[5]: ExtractResult(subdomain='', domain='[2001', suffix='')
```

Do you think it's possible to add it?

Thanks a lot.
Regards

**Comment by hangtwenty** [comment]
@flock3 this seems like an impedance mismatch. why do you want to tldextract ipv6? (the fact that ipv4 'works' may just be coincidence, I'm not totally sure)

**Comment by hangtwenty** [comment]
if you are trying to throw a large list of inputs that may be a mix of hostnames and IPv4/IPv6, and maybe initially they're all jumbled together ... well, you could solve by doing your own handling before calling tldextract, that separates ipv4 and ipv6 into their own groups. ipv6 would just skip tldextract completely

**Comment by hangtwenty** [comment]
Closing because old (and we had the "needs clarification" label on it for a while; and it is a job for preprocessing)
