### ISSUE TITLE
Weird bug with dashes and .de

### ISSUE THREAD

**Issue by foxx** [john-kurkowski/tldextract#157]
DE broken

```
>>> tldextract.extract('homewebserver.de')
ExtractResult(subdomain='', domain='homewebserver', suffix='de')
>>> tldextract.extract('home-webserver.de')
ExtractResult(subdomain='', domain='', suffix='home-webserver.de')
```

COM works fine

```
>>> tldextract.extract('home-webserver.com')
ExtractResult(subdomain='', domain='home-webserver', suffix='com')
>>> tldextract.extract('homewebserver.com')
ExtractResult(subdomain='', domain='homewebserver', suffix='com')
```

seems to work regardless of PSL on or off.

**Comment by hangtwenty** [comment]
Appears that this is related to changes in the actual PSL

You mentioned it seems to be the same regardless of whether PSL is on or off, but did you set `fallback_to_snapshot=False`? it has a baked-in snapshot it falls back to - as graceful degradation in case there is an issue getting up-to-date PSL. that snapshot can be older and maybe something's changed about the DSL's rules for `de`

**Comment by hangtwenty** [comment]
```python
# to test, creating an instance where cache and snapshot or disabled (gets up to date PSL every time)
In [7]: from tldextract import TLDExtract
In [8]: extract = TLDExtract(cache_file=None, fallback_to_snapshot=None)

In [9]: extract('home-webserver.com')
Out[9]: ExtractResult(subdomain='', domain='home-webserver', suffix='com')

In [11]: extract('homewebserver.de')
Out[11]: ExtractResult(subdomain='', domain='homewebserver', suffix='de')

In [12]: extract('home-webserver.de')
Out[12]: ExtractResult(subdomain='', domain='home-webserver', suffix='de')
```

**Comment by hangtwenty** [comment]
Marked as `hold: a PR is waiting`, because there is a PR #144 which will be updating the snapshot to latest. (if that does not get merged soon, we can just do a change to update the snapshot..)

**Comment by john-kurkowski** [comment]
This is not unique to .de or .com suffixes. This is unique to home-webserver.de. [It is in the private section of the PSL](https://github.com/publicsuffix/list/blob/0e2a405f597a3c1be456d704b42bdd5e0d4954bb/public_suffix_list.dat#L11409). Read more about public vs. private [in the README](https://github.com/john-kurkowski/tldextract/tree/2.2.0#public-vs-private-domains). This is expected.

**Comment by hangtwenty** [comment]
@john-kurkowski 🙌 good catch! I need to remember to grep the PSL _every time_ a case is mentioned, hehe
