### ISSUE TITLE
minor release

### ISSUE THREAD

**Issue by hangtwenty** [john-kurkowski/tldextract#160]
we could cut a minor release

making this ticket mostly as a memo for @hugovk 's helpful reminder from #152

> You're welcome! Make sure to update tools before release so the metadata is included in the package, eg.:
> 
>     pip install -U pip setuptools twine wheel
> 
> https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/

**Comment by john-kurkowski** [comment]
👍 Done in d40fc51
