### ISSUE TITLE
Missed Tlds

### ISSUE THREAD

**Issue by ebubekirbbr** [john-kurkowski/tldextract#161]
com.am and tsk.tr tlds can not be splitted by the extract function.

for example abc.com.am is splitted into 

registered domain: com.am
suffix: am
subdomain:abc

I think that adding these tlds to the tld list solves the problem.

**Comment by hangtwenty** [comment]
Please follow the README to ensure your suffix list is up to date. The suffix list is a third-paety artifact and we do not make any additions/subtractions.

The README also lets you know how to customize to your own file, so you can get the up to date list then do this modification if you need to.

If/when you have tried these things, if there is a reproducible bug, let us know. I am closing until then.
