### ISSUE TITLE
tldextract with own tld and url list

### ISSUE THREAD

**Issue by maravento** [john-kurkowski/tldextract#165]
how to use tldextract with my own url list (and my own tld list instead of publicsuffix), and redirect to > out

format my-url-list:

.xxx.vertigodiz.hop.clickbank.net
.writing777.hop.clickbank.net
.blabla.btinternet.co.uk
.drive.google.com
etc

format my-tlds-list:

.aaa
.aarp
.abarth
.ac.ir
.ac.jp
.ac.mw
.ac.nz
.aco
etc

**Comment by john-kurkowski** [comment]
See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/2.2.1#specifying-your-own-url-or-file-for-the-suffix-list-data). Loop over your input lines, call your `TLDExtract` instance with each line, and `print` what you want.

**Comment by maravento** [comment]
> See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/2.2.1#specifying-your-own-url-or-file-for-the-suffix-list-data). Loop over your input lines, call your `TLDExtract` instance with each line, and `print` what you want.
Already did. It did not work Could you give a concrete example? Thank you

**Comment by john-kurkowski** [comment]
What do you mean it did not work? Was there unexpected output? Was there an uncaught error? Please provide a minimal, self-contained, and reproducible example. Show full input and output.

I'll whip up an example on my end.

**Comment by john-kurkowski** [comment]
Here's an example. I took [a handful of suffixes from the head of the PSL](https://github.com/publicsuffix/list/blob/8acaea05268ed619cf644a6749949b580ed47ea3/public_suffix_list.dat#L13-L19).

```zsh
$ echo 'ac
com.ac
edu.ac
gov.ac
net.ac
mil.ac
org.ac' > my-psl.txt
$ python
Python 3.7.3 (default, Jul 11 2019, 17:31:25)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tldextract
>>> extract = tldextract.TLDExtract(suffix_list_urls=['file:///my-psl.txt'])
>>> for url in ('google.com', 'google.com.ac', 'google.com.uk'):
...     print(extract(url))
...
ExtractResult(subdomain='', domain='google', suffix='com')
ExtractResult(subdomain='', domain='google', suffix='com.ac')
ExtractResult(subdomain='google', domain='com', suffix='uk')

**Comment by john-kurkowski** [comment]
I edited my example after I realized it was still picking up the bundled suffix list. I didn't use all the constructor args the README suggested. This lib is silent about errors reading that file. 🤦‍♂ Maybe this is the wall you were hitting.

**Comment by maravento** [comment]
You still have not answered my question

**Comment by maravento** [comment]
That is not what I asked. I'll close the ticket because it does not make sense anymore, because you assumed that you answered correctly and it was not like that. Thank you.
