### ISSUE TITLE
More TLD's than available in ICANN

### ISSUE THREAD

**Issue by naga7773** [john-kurkowski/tldextract#166]
I am extracting the TLD's of the domains obtained from Alexa top 1 million websites, and I am seeing a total of 1938 TLD's from my dataset. But, according to ICANN, as of July 23, 2019, there are only 1530 TLD's available. 

datasource: https://www.kaggle.com/cheedcheed/top1m
ICANN list: http://data.iana.org/TLD/tlds-alpha-by-domain.txt
 
Some of the TLD's identified in the dataset are: qld.gov.au,  vic.gov.au . In these two cases, there is nothing in the subdomain and domain part. Everything is identified as TLD.  I believe, 'qld' should be returned as the domain. 
--

**Comment by john-kurkowski** [comment]
> I am extracting the TLD's

Extracting using tldextract? Note this library doesn't emit TLDs. It only emits subdomain, domain, and suffix:

```python
>>> tldextract.extract('https://www.qld.gov.au/')
ExtractResult(subdomain='', domain='www', suffix='qld.gov.au')
```

For your use case, sounds like you could take `suffix` there, split by `.`, and use the last token.

**Comment by john-kurkowski** [comment]
> Note this library doesn't emit TLDs.

Despite the library's name. A legacy misnomer. 😛

**Comment by john-kurkowski** [comment]
I think I clarified what's going on, that it's working as intended, and a way to get what the OP wants.
