### ISSUE TITLE
Potential dependency conflicts between tldextract and idna

### ISSUE THREAD

**Issue by NeolithEra** [john-kurkowski/tldextract#167]
Hi, as shown in the following full dependency graph of  **_tldextract_**, **_tldextract_** requires _**idna**_ (the latest version)， while the installed version of **_requests_**(2.22.0) requires _**idna>=2.5,<2.9**_.

According to Pip's “first found wins” installation strategy, _**idna 2.8**_ is the actually installed version.  

Although the first found package version _**idna 2.8**_ just satisfies the later dependency constraint (_**idna>=2.5,<2.9**_), it will lead to a build failure once developers release a newer version of **_idna_**.

### Dependency tree--------
```
+-tldextract(version range:)
| +-setuptools(version range:)
| +-idna(version range:)
| +-requests(version range:>=2.1.0)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-requests-file(version range:>=1.4)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependencies to be **_idna>=2.5,<2.9_** and **_requests==2.22.0_**, to remove this conflict. 
        I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency **_idna_**, and use the library **_idna_** transitively introduced by **_requests_**.

As there are a lot of downstream projects depending on **_tldextract_**, solution 1 may introduce conflicts into them. 
Personally, I prefer solution 2. 
What's your opinion?

@john-kurkowski May I pull a request to solve this issue?

**Comment by john-kurkowski** [comment]
Agreed, solution 2 sounds better. PR welcome.

Curious, how did you find this? Was this conflict already giving you trouble?

**Comment by john-kurkowski** [comment]
> Curious, how did you find this? Was this conflict already giving you trouble?

Relatedly, what happens if we do nothing? Some day, users of this library will have to manually pin their version of `idna`?

**Comment by NeolithEra** [comment]
Thanks for you attention.
As the existing tools cannot provide the full dependency graph of Python projects like what Maven does for Java,
I develop a tool that  can "dig" all of the dependencies specified in your requirement files, and print the full dependenfy graph for users.
The full dependenfy graph allows us to see the full conflicts picture, even we have not installed it.
The process can help developers diagnose dependency conflicts problem.

Hope this answer can solve your concern.

Best, 
Neolith

**Comment by john-kurkowski** [comment]
I decided against any action here. The CI failure on your PR reminded me this is thorny. Also, things are working as they are. If it becomes a real problem and for more people, we can revisit. Sorry to send you on that errand.
