### ISSUE TITLE
Is the public suffix list updated?

### ISSUE THREAD

**Issue by ealashwali** [john-kurkowski/tldextract#170]
Hi. Thanks for offering this library. I have an important question plz and I will appreciate your answer. 

Now the code relies on the public suffix list provided [here](https://www.publicsuffix.org/). Is this list still maintained today? By looking at the copyright of that page at the bottom, it says: `Copyright © 2007–16`. Can you plz confirm if you have any idea that the list is maintained todate?  

If so, my understanding is that to maintain it updated, all I have to do is: `tldextract --update`?

**Comment by john-kurkowski** [comment]
Yep. If you follow their link to the list's GitHub, [publicsuffix/list](https://github.com/publicsuffix/list), you'll see recent commits and merged pull requests. You got the update command right.

**Comment by ealashwali** [comment]
Thanks. I get a segmentation fault when I execute the command. Does deleting the cache list as stated in the home page of tldextract will provide me with an updated list?

**Comment by john-kurkowski** [comment]
Let's concentrate the segmentation fault discussion in #171.

**Comment by ealashwali** [comment]
Thanks. I am unable to identify the source of the segmentation fault that I pointed [here](https://github.com/john-kurkowski/tldextract/issues/171). 
So meanwhile I have to find another way to keep the list updated. Does deleting this file before running my code that uses the tldextract:
/home/e/.local/lib/python3.6/site-packages/tldextract/.tld_set
does the purpose? I just want to make sure that this is the case as it is important to have an updated list. Thanks.

**Comment by john-kurkowski** [comment]
Yes. Deleting that file is essentially what the CLI `--update` flag [does](https://github.com/john-kurkowski/tldextract/blob/2.2.1/tldextract/tldextract.py#L270). It also refetches the file. If the file is missing on first run, it'll be refetched then.
