### ISSUE TITLE
"Segmentation fault (core dumped)" when running "tldextract --update"

### ISSUE THREAD

**Issue by ealashwali** [john-kurkowski/tldextract#171]
I have Ubuntu 18.04.3 LTS. I installed tldextract using: `pip3 install tldextract` 

The library seems installed correctly as I am able to import it in python3 script. However, I want to get an updated public suffix list. So I run: 
`tldextract --update`

but I get this error:
`Segmentation fault (core dumped)`

As per recommended in the README, I already deleted the following two files as I want to fetch updated ones:
/home/myuser/.local/lib/python3.6/site-packages/tldextract/.tld_set_snapshot
/home/myuser/.local/lib/python3.6/site-packages/tldextract/.tld_set

How can I resolve the `tldextract --update` issue so I can fetch an updated public suffix list?

**Comment by john-kurkowski** [comment]
Huh. Never seen that from this project. Without a repro or traceback, hard to imagine what it could be. [This SO thread has a good explanation of the error message.](https://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped) You can narrow down what's causing your crash by stepping over this project's source lines in a debugger. More directly, it looks like you could force a traceback via the standard library [faulthandler](https://docs.python.org/3/library/faulthandler.html).

**Comment by hangtwenty** [comment]
Opinionated take: in my experience this never indicated an issue in the code I was calling, and always indicated an environment issue. Like an under-provisioned machine or a bad installation of Py
