### ISSUE TITLE
bash script syntax issue / bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by raramuridesign** [john-kurkowski/tldextract#176]
Hi 
we are running this command and get the error below

COMMAND
**extract = tldextract.TLDExtract(suffix_list_urls=[f'file://{os.path.abspath("domains.csv")}'], cache_file=None, fallback_to_snapshot=False)**

ERROR

**bash: syntax error near unexpected token `('**

Could you explain what we are doing wrong here
Thanks
Matthew

**Comment by john-kurkowski** [comment]
That command doesn't look like a Bash command. It looks like Python source code. Try running it inside a Python interpreter or script.

**Comment by raramuridesign** [comment]
Solved
