### ISSUE TITLE
. Is converted to a space

### ISSUE THREAD

**Issue by GodEunhyuk** [john-kurkowski/tldextract#183]
Respectfully,
I use it well.

. Is converted to a space
Can't stop it?

For example
google.com
-> google com

**Comment by john-kurkowski** [comment]
Looks like you’re running from the CLI? Like this:

```
$ tldextract google.com
 google com
```

That is expected. That is the purpose of this project, to split the input into 3 parts, subdomain, domain, and public suffix. At the CLI, the 3 parts are separated by space.

**Comment by john-kurkowski** [comment]
So, working as expected. Let me know if I can clarify further.
