### ISSUE TITLE
Type Stubs

### ISSUE THREAD

**Issue by kkirsche** [john-kurkowski/tldextract#189]
It would be awesome if the project could include type stubs for Python 3 to satisfy type check tools such as mypy

**Comment by hangtwenty** [comment]
PRs welcome

**Comment by cdpierse** [comment]
I'd be happy to have a go with this and add some type hinting.

**Comment by domdfcoding** [comment]
Hi @cdpierse, wondering whether you've made any progress with the type hints yet?
