### ISSUE TITLE
[bug] Commas and spaces in subdomain

### ISSUE THREAD

**Issue by ddelange** [john-kurkowski/tldextract#195]
Hi! No expert here, but I'm pretty sure <`, `> is not allowed in a fqdn (but please prove me wrong!).

```py
In [3]: import tldextract
In [4]: tldextract.extract('vzksm.ru, www.wzksm.ru')
Out[4]: ExtractResult(subdomain='vzksm.ru, www', domain='wzksm', suffix='ru')
```

**Comment by hangtwenty** [comment]
An invalid domain name means it's an invalid URL. ⌘+F for "invalid URL" in the README. tldextract is designed to accept your inputs rather than add overhead of imposing its own validators.
