### ISSUE TITLE
Three teir TLD incorrectly sliced

### ISSUE THREAD

**Issue by harrisonSoS** [john-kurkowski/tldextract#202]
**Expected result:**
```
>>> tldextract.extract("prod.environment.nsw.gov.au")
ExtractResult(subdomain='prod', domain='environment', suffix='nsw.gov.au')
```
**Actual result:**
```
>>> tldextract.extract("prod.environment.nsw.gov.au")
ExtractResult(subdomain='prod.environment', domain='nsw', suffix='gov.au')
```
It may be getting confused because `.gov.au` is a TLD, but so is `.nsw.gov.au`
The solution may be to match the longest possible TLD first and keep dropping levels until successful.

**Comment by john-kurkowski** [comment]
Looks like the PSL doesn't consider nsw.gov.au a public suffix. It did 10 years ago though. https://github.com/publicsuffix/list/commit/ea4fe99831b05d4c372afd5404ae74cc95966d77

**Comment by harrisonSoS** [comment]
Thanks for that link, I'll chase it upstream. Cheers!
