### ISSUE TITLE
Allow cache_file argument to also accept list

### ISSUE THREAD

**Issue by hibare** [john-kurkowski/tldextract#204]
Problem: We have an application, which perform TLD operation using celery workers. As we have a couple of celery workers, whenever cache_file update is called, it only updates the file in instances of the celery worker which picked up that task.
So, there is content difference across all the celery instances. 

If the tldextract can accept list as cache_file argument, essentially that list can be stored in redis and any worker can pick up easily.

**Comment by john-kurkowski** [comment]
Relatedly, #144 changes the cache file name to a directory name.

**Comment by john-kurkowski** [comment]
Can you say more why the list fixes your issue?

Is this a worker ops issue? Does this pseudocode work?

```
# Instead of …
all_celery_workers.enqueue(`tldextract --update`)

# Do this …
for worker in all_celery_workers:
  worker.exec(`tldextract --update`)
```

**Comment by hibare** [comment]
This will not be efficient if a worker disconnects temporary or a new worker is added between the update gap time

**Comment by john-kurkowski** [comment]
Ok, can you say more why the list fixes your issue? What would it look like?

**Comment by hibare** [comment]
Assume there are 5 celery workers and we are updating list independent of this module. This provide the flexibility to cache the latest PSL data into a cache such as redis. We can pass list from cache to the module without worrying worker has the update

**Comment by john-kurkowski** [comment]
To be clear, what would it look like?

**Comment by john-kurkowski** [comment]
In the meantime, [`suffix_list_urls` can be a local file](https://github.com/john-kurkowski/tldextract/tree/3.0.2#specifying-your-own-url-or-file-for-the-suffix-list-data). You could dump raw PSL text content from your Redis into a tempfile. Pass that tempfile path in `suffix_list_urls`.

**Comment by hibare** [comment]
yeah, my current method is this

**Comment by john-kurkowski** [comment]
Closing due to lack of response why the list fixes the issue / what it would look like
