### ISSUE TITLE
Request: Could scheme be made available?

### ISSUE THREAD

**Issue by JeffreyShran** [john-kurkowski/tldextract#205]
Hi,

I'm aware of https://github.com/john-kurkowski/tldextract/issues/6 which asked for some urlparse functionality. This isn't that. It's simply a request to include access to the scheme as part of the standard output. 

So instead of:
```
tldextract.extract('https://blogs.google.com')
# ExtractResult(subdomain='blogs', domain='google', tld='com')
```
Do this instead:
```
tldextract.extract('https://blogs.google.com')
# ExtractResult(scheme='https', subdomain='blogs', domain='google', tld='com')
```

**Comment by john-kurkowski** [comment]
Possible. We're already parsing the scheme. We're considering moving away from `namedtuple`, to track additional metadata, like in #138. If we make that break, then adding the scheme wouldn't break this library's expected, ordered triple of `(subdomain, domain, tld)`.

**Comment by JeffreyShran** [comment]
Thanks @john-kurkowski.

Yes, if you could please keep in the back of your mind that would be great.

**Comment by john-kurkowski** [comment]
https://github.com/john-kurkowski/tldextract/issues/272#issuecomment-1267491864
