### ISSUE TITLE
please release new pypi version supporting include_psl_private_domains=True

### ISSUE THREAD

**Issue by wumpus** [john-kurkowski/tldextract#208]
I'm thrilled to see the new code! But it still isn't on pypi. Please close this issue when released, so folks have an easy way to get notified. Thanks.

**Comment by john-kurkowski** [comment]
Thanks for the excitement and for tracking this! It's now published in [3.0.0.rc1](https://github.com/john-kurkowski/tldextract/releases/tag/3.0.0.rc1). I'll let it marinate for a few days and release 3.0.0. I don't expect much to change.

**Comment by john-kurkowski** [comment]
I'll be open about the rudimentary analytics and QA process I have. These PyPI download stats:

* https://pepy.tech/project/tldextract
* https://pypistats.org/packages/tldextract

They're fascinating. 100s of downloads for the new RC, vs. 10,000s for the old versions. At what number will I feel assured, "Okay, I didn't screw up everybody?" 😅   :philosoraptor:

**Comment by wumpus** [comment]
Hey, if you have good tests, and if you can see a bunch of RC downloads... might as well go for it.

**Comment by john-kurkowski** [comment]
My logic exactly. Released [3.0.0](https://github.com/john-kurkowski/tldextract/releases/tag/3.0.0).
