### ISSUE TITLE
tldextract --update fails if called with --cache_dir

### ISSUE THREAD

**Issue by sebastian-nagel** [john-kurkowski/tldextract#215]
```
$> tldextract --update --cache_dir /tmp/tldcache
Traceback (most recent call last):
  File "/usr/local/bin/tldextract", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tldextract/cli.py", line 35, in main
    tld_extract.cache_file = args.cache_file
AttributeError: 'Namespace' object has no attribute 'cache_file'
```

The variable `cache_file` [cli.py, line 35](https://github.com/john-kurkowski/tldextract/blob/5e3b660010dcb1271081fba0c58f90848433149a/tldextract/cli.py#L35) needs to be renamed as well.

However, I've applied this little fix but the custom cache is still not used. Instead, the global cache is updated.

**Comment by john-kurkowski** [comment]
Good catch! Thanks for the info!
