### ISSUE TITLE
Wrong extracted domain "www"

### ISSUE THREAD

**Issue by ykhatami** [john-kurkowski/tldextract#219]
The extract function returns "www" as domain name for a specific domain. Not sure if this is a single domain issue or a larger problem. 

tldextract.extract("https://www.nhs.uk/")
returns 
ExtractResult(subdomain='', domain='www', suffix='nhs.uk')

Expected return:
ExtractResult(subdomain='', domain='nhs', suffix='uk')

**Comment by stonecrusher** [comment]
But it's correct.
`.nhs.uk` is a valid ICANN registered suffix.
https://en.wikipedia.org/wiki/.uk#Second-level_domains
[Public Suffix List](https://publicsuffix.org/list/) line 6426

**Comment by ykhatami** [comment]
This is a weird one. I see your point, but www.nhs.uk is a website on its own. And the domain extracted by tldextract is www. Wondering what’s the best way to handle this.

**Comment by hangtwenty** [comment]
> This is a weird one. I see your point, but [www.nhs.uk](http://www.nhs.uk) is a website on its own. And the domain extracted by tldextract is [www](http://www). Wondering what’s the best way to handle this.

Preprocessing is the best way IMHO

That's a really special case so preprocessing is probably the best way. Wrap your call to tldextract and handle your special cases before/after as needed
