### ISSUE TITLE
Question: how to exclude a TLD to deem it as not allowed/valid?

### ISSUE THREAD

**Issue by ambersariya** [john-kurkowski/tldextract#221]
How can we exclude a tld from the PSLs loaded by the library, is there a setting for that?

**Comment by john-kurkowski** [comment]
Hm. I don't think there is. There's only a way to add your own suffix or a whole suffix list. See [this FAQ entry](https://github.com/john-kurkowski/tldextract/tree/3.1.0#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____). As a workaround, you could read in the PSL yourself, exclude the suffixes in the raw text, then pass the filtered list via that FAQ's method.
