### ISSUE TITLE
missed .eu.com

### ISSUE THREAD

**Issue by JerryPan** [john-kurkowski/tldextract#223]
tldextract.extract('www.elitejobs.eu.com')
ExtractResult(subdomain='www.elitejobs', domain='eu', suffix='com')

This is not correct, 'eu.com' is a valid suffix per https://publicsuffix.org/list/public_suffix_list.dat

**Comment by JerryPan** [comment]
I don't know why but it missed other top level suffix, like 'xxx.uk.com'  Did I missed something?

**Comment by john-kurkowski** [comment]
I notice your suffix is toward the bottom of the PSL. It's a private domain. You must opt into parsing those. See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/3.1.0#public-vs-private-domains).
