### ISSUE TITLE
filter domain not ok?

### ISSUE THREAD

**Issue by hzbd** [john-kurkowski/tldextract#224]
```
In [28]: domain = "socialsecurity.gov.scot"

In [29]: ext = tldextract.extract(domain)

In [30]: ext
Out[30]: ExtractResult(subdomain='socialsecurity', domain='gov', suffix='scot')
```

**Comment by john-kurkowski** [comment]
What is the expected output?

I notice your domain is in the private section of the PSL, toward the bottom. You must opt into parsing private domains. See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/3.1.0#public-vs-private-domains).

**Comment by hzbd** [comment]
@john-kurkowski  Thank you for your reply.

It may be that I misunderstood. The screenshot below is the result I expected.

![image](https://user-images.githubusercontent.com/3000843/120803623-52bf1780-c576-11eb-86af-82a506d0413c.png)

**Comment by john-kurkowski** [comment]
Cool. I think this optional behavior is explained by my README link then.
