### ISSUE TITLE
check if tld exists 

### ISSUE THREAD

**Issue by sevmardi** [john-kurkowski/tldextract#225]
thank you for this library. 

is there a way to check if a given tld (suffix) actually exists? 

e.g. 
Given a domain name ```morningcoffee.asdbn``` I want to check if this tld exists. Can this be done using this library? if so how?

**Comment by john-kurkowski** [comment]
You can test the `suffix` property.

```py
if tldextract.extract('morningcoffee.asdbn').suffix:
    print('It exists')
else:
    print('It does not exist')
```

**Comment by sevmardi** [comment]
works thanks!
