### ISSUE TITLE
Incorrect suffix extracted while in public suffix list

### ISSUE THREAD

**Issue by freekklein** [john-kurkowski/tldextract#226]
Expected that each suffix in https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat will be extracted correctly.

**As intended**
``` 
tldextract.extract('test.co.uk')
ExtractResult(subdomain='', domain='test', suffix='co.uk')
```

**As intended**
``` 
tldextract.extract('test.org.ba')
ExtractResult(subdomain='', domain='test', suffix='org.ba')
```

**Not intended**
``` 
tldextract.extract('test.co.no')
ExtractResult(subdomain='test', domain='co', suffix='no')
```

**Comment by john-kurkowski** [comment]
I notice your domain is in the private section of the PSL, toward the bottom. You must opt into parsing private domains. See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/3.1.0#public-vs-private-domains).
