### ISSUE TITLE
Question: is there any other rules for specifying local file for suffix_list_urls ?

### ISSUE THREAD

**Issue by onaeonae2** [john-kurkowski/tldextract#228]
i'm trying to specify sufflix_list_urls with my local files follwing example in README
i downloaded public suffix list from [https://publicsuffix.org/list/public_suffix_list.dat](url) as sufflix_list.dat
and make extract like code below
```
    extract = tldextract.TLDExtract(
        suffix_list_urls=[
            "file://C:/myabsolutepath/test/configs/suffix_list.dat"
        ],
        fallback_to_snapshot=False,
    )
```
but it has error below
`ValueError: file: URLs with hostname components are not permitted`

is there something wrong with my code? i added file:// but it's not working.

help me how to specify local file as suflix_list_urls

**Comment by onaeonae2** [comment]
i tried different way. but it doesn't work

after i changeds suffix_list_urls like this
```
  extract = tldextract.TLDExtract(
        suffix_list_urls=[
            "file:///C:/myabsolutepath/test/configs/suffix_list.dat"
        ],
        fallback_to_snapshot=False,
    )
```
returns different error below
```
requests.exceptions.HTTPError: 404 Client Error: None for url: None
No Public Suffix List found. Consider using a mirror or constructing your TLDExtract with `suffix_list_urls=None`
```
i thougt maybe it's not possible to handle local file for some unkown reasons in module
so i inspected cache.py. _fetch_urls
and it's response returns "**there is no such file or directory"** while file exists properly (i checked it by enter url file:///path in browser)

i don't know why this happens and how to use my local suffix list for tldextract
please help

**Comment by john-kurkowski** [comment]
> so i inspected cache.py. _fetch_urls

Cool, you found the line in this library that uses the `file://` URL.

https://github.com/john-kurkowski/tldextract/blob/0b876fa863bc54fa86c2a4d8b4f58391873e2281/tldextract/cache.py#L203

You see this library is not doing anything special with the URL. We pass it on unaltered to the 3rd party library to fetch. So probably an issue with the 3rd party library.

> `URLs with hostname components are not permitted`

I Googled your error message. [It is indeed in a 3rd party library, requests-file](https://github.com/dashea/requests-file/blob/1.5.1/requests_file.py#L34). I searched their issue tracker for Windows mentions. There's a thread with a similar question to yours, how to encode `file://` URLs for Windows: https://github.com/dashea/requests-file/issues/5. Give that a try?

**Comment by onaeonae2** [comment]
Thank You for your support
yesterday i fixed it temporarily with no fetch example in README (no local file)
maybe i should try it again with example you told today
