### ISSUE TITLE
bad parsing

### ISSUE THREAD

**Issue by erpatrik** [john-kurkowski/tldextract#237]
Hi,
found 2 issues while parsing domains.

`tldextract.extract("hokkaido.jp")`
ExtractResult(subdomain='', domain='', suffix='hokkaido.jp')

`tldextract.extract("ketrzyn.pl")`
ExtractResult(subdomain='', domain='', suffix='ketrzyn.pl')

**Comment by ShmuelTreiger** [comment]
Having the same issue with `ne.jp`

**Comment by ShmuelTreiger** [comment]
These are all suffixes on the public sources list. That's why it's like this.

https://publicsuffix.org/list/public_suffix_list.dat

**Comment by brycedrennan** [comment]
@erpatrik, @ShmuelTreiger is correct, the domains you're testing are in the public sufffix list so this library is correctly returning them as such.
