### ISSUE TITLE
in-addr.arpa not extracting as expected

### ISSUE THREAD

**Issue by smellyspice** [john-kurkowski/tldextract#241]
I've seen this in two different modules now, not sure why this is: 

Code: 
```
print(tldextract.extract('subdomain.domain.com'))
print(tldextract.extract('8.8.8.8.in-addr.arpa'))
```
Result: 
```
ExtractResult(subdomain='subdomain', domain='domain', suffix='com')
ExtractResult(subdomain='8.8.8', domain='8', suffix='in-addr.arpa')
```
I would have expected `in-addr.arpa` to return something like: 
```
ExtractResult(subdomain='8.8.8.8', domain='in-addr', suffix='arpa')
```
What am I doing wrong? :)

**Comment by john-kurkowski** [comment]
`in-addr.arpa` is indeed a public suffix, [according to the list](https://github.com/publicsuffix/list/blame/d33fcc3e0470e8eab5fa8270933a231a13909ff9/public_suffix_list.dat#L199). See also [this project's FAQ](https://github.com/john-kurkowski/tldextract/blob/3.1.2/README.md#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____). 

(Interesting suffix. It's near the top of the list. It's been there for at least 15 years, according to the blame. An oldie!)
