### ISSUE TITLE
Incorrectly parsing this exact domain: veterinaire.fr

### ISSUE THREAD

**Issue by JonathanAquino-NextRoll** [john-kurkowski/tldextract#261]
When I try to apply tldextract to veterinaire.fr, it says the domain is '' and the suffix is 'veterinaire.fr':

    >>> print(tldextract.extract('veterinaire.fr'))
    ExtractResult(subdomain='', domain='', suffix='veterinaire.fr')

Oddly, if I remove the last letter from veterinaire, it works:

    >>> print(tldextract.extract('veterinair.fr'))
    ExtractResult(subdomain='', domain='veterinair', suffix='fr')

And if I add 2 to veterinaire, it also works:

    >>> print(tldextract.extract('veterinaire2.fr'))
    ExtractResult(subdomain='', domain='veterinaire2', suffix='fr')

**Comment by brycedrennan** [comment]
Yes veterinaire.fr is a top-level domain according to the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat#:~:text=fr%0Aport.fr-,veterinaire,-.fr%0A%0A//%20ga%20%3A%20https)
