### ISSUE TITLE
Parsing without PSL still uses PSL for some FQDNs

### ISSUE THREAD

**Issue by jonmartz** [john-kurkowski/tldextract#262]
Hi, we ran into the following issue:

- `tldextract.extract('kawasaki.jp', include_psl_private_domains=False)` produces `ExtractResult(subdomain='', domain='kawasaki', suffix='jp')`, which is fine.
- `tldextract.extract('www.kawasaki.jp', include_psl_private_domains=False)` produces `ExtractResult(subdomain='', domain='', suffix='www.kawasaki.jp')`, which would be expected if `include_psl_private_domains=True` because "*.kawasaki.jp" is a valid suffix according to the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat). But why is the result the same when this parameter is set to `False`, given that without the "www" prefix the resulting suffix is only "jp"?

Thanks!

**Comment by john-kurkowski** [comment]
> without PSL

I think you're reading the `include_psl_private_domains` parameter as controlling whether this project uses the PSL to parse domains, or uses something else to parse domains. The parameter actually controls whether PSL private domains are distinguished from public domains. See [this section of the README](https://github.com/john-kurkowski/tldextract/tree/3.2.0#public-vs-private-domains). The rule for [kawasaki.jp occurs early in the list](https://github.com/publicsuffix/list/blob/a71975f1c5f0097bbbcd78862df5e762c23ace91/public_suffix_list.dat#L1956), so it is not in the private domain section, and wouldn't be affected by the parameter.

**Comment by jonmartz** [comment]
Thank you very much for the quick response, which resolves our issue.
