### ISSUE TITLE
Can I add a custom suffix  'cn.com'

### ISSUE THREAD

**Issue by pwnhxl** [john-kurkowski/tldextract#264]
> tldextract.extract("izhuye.qq.cn.com").domain
'cn'

> tldextract.extract("izhuye.qq.cn.com").suffix
'com'

cn.com is suffix

**Comment by john-kurkowski** [comment]
Yes. See [this FAQ entry](https://github.com/john-kurkowski/tldextract/tree/3.2.1#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____).
