### ISSUE TITLE
Suffix issue

### ISSUE THREAD

**Issue by avramd02** [john-kurkowski/tldextract#268]
When trying to strip certain urls its returning the wrong suffix. 

tldextract.extract("http://blahblah.uk.com/blah/blah")
ExtractResult(subdomain='blahblah', domain='uk', suffix='com')

When in reality it should be returning domain = blahblah and suffix = uk.com
uk.com is in the public suffix list.

**Comment by john-kurkowski** [comment]
That suffix is pretty far down the list, [on line 10970](https://github.com/publicsuffix/list/blob/edb31b6dedae4ed317a18d77cddc75e75ce776e3/public_suffix_list.dat#L10970), so it's in the private domains section. See [the FAQ](https://github.com/john-kurkowski/tldextract/blob/3.3.0/README.md#public-vs-private-domains).

**Comment by avramd02** [comment]
I see, thanks.
