### ISSUE TITLE
The TLD .com.ru is handled incorrectly

### ISSUE THREAD

**Issue by hkopp** [john-kurkowski/tldextract#270]
Hi,
I have encountered a bug when handling .com.ru domains.
```
In [1]: import tldextract

In [2]: tldextract.extract('http://lamy.com.ru/')
Out[2]: ExtractResult(subdomain='lamy', domain='com', suffix='ru')
```

I would have expected the following:
```
Out[2]: ExtractResult(subdomain='', domain='lamy', suffix='com.ru')
```
.com.ru is in the list of public suffixes, so this is clearly a bug: https://publicsuffix.org/list/public_suffix_list.dat

Thanks for creating the library by the way. I first tried sed with increasingly complex regular expressions, but that quickly grew out of hand. Your library was exactly what I needed.

**Comment by hkopp** [comment]
And my version number:
```
In [5]: tldextract.__version__
Out[5]: '3.3.1'
```

**Comment by john-kurkowski** [comment]
Thanks for the thorough diagnostic info! That suffix [is pretty far down the list](https://github.com/publicsuffix/list/blob/edb31b6dedae4ed317a18d77cddc75e75ce776e3/public_suffix_list.dat#L11783), so it's in the private domains section. See [the FAQ](https://github.com/john-kurkowski/tldextract/blob/3.3.0/README.md#public-vs-private-domains).
