### ISSUE TITLE
Adding this project to the PSL website

### ISSUE THREAD

**Issue by axoroll7** [john-kurkowski/tldextract#271]
The visibility of this library could be greatly increased if the library were referenced on the PSL website, at the end of this webpage : https://publicsuffix.org/learn

I had a lot of trouble finding this library. Before that, I used other libraries to which I added an automatic update system. I found this library by chance on a github project based on Qt. Could someone sends a little message on their mailing list to ask them to reference this library ? https://groups.google.com/forum/#!forum/publicsuffix-discuss

**Comment by john-kurkowski** [comment]
Thanks for the suggestion! publicsuffix/publicsuffix.org#40
