### ISSUE TITLE
Some bad case like www.edu.cn

### ISSUE THREAD

**Issue by likohank** [john-kurkowski/tldextract#276]
www.gov.hk, www.edu.cn, www.gov.cn 
show wrong result.

**Comment by john-kurkowski** [comment]
What is your expected/actual?

However, I'm thinking this is not an issue in this project. See [this FAQ entry](https://github.com/john-kurkowski/tldextract/tree/3.4.0#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____). 

Note the PSL includes all 3 of your examples specifically. [Here's gov.hk](https://github.com/publicsuffix/list/blob/b5963e9df475e7c7dee6dec88ea32dbd6df6cdeb/public_suffix_list.dat#L1205), for example.
