### ISSUE TITLE
FDQN Extraction error in some domains

### ISSUE THREAD

**Issue by danruggi** [john-kurkowski/tldextract#281]
Error in extraction for 

 - subdomain.domain.com.de
 - domain.com.de
 - subdomain.domain.com.se
 - domain.com.se

com.de and com.se are valid tld from the Public Domains List, but can't be recognized by the extractor;

Example:
```
import tldextract
tldextract.extract('http://forums.test123.com.de/')
ExtractResult(subdomain='forums.test123', domain='com', suffix='de')
```

A website that use this, ie: 
https://herbalife(dot)com(dot)se/
(hidden to avoid backlinks)

**Comment by john-kurkowski** [comment]
See [this FAQ entry](https://github.com/john-kurkowski/tldextract#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____) and [this explanation of public vs. private domains](https://github.com/john-kurkowski/tldextract/blob/3.4.0/README.md#public-vs-private-domains).

**Comment by danruggi** [comment]
Hi, thanks for the answer,
I opened the issue because com.de and com.se are listed in the PSL

**Comment by danruggi** [comment]
extractor = tldextract.TLDExtract(include_psl_private_domains=True)
