### ISSUE TITLE
IPv4 with non-ASCII dots

### ISSUE THREAD

**Issue by elliotwutingfeng** [john-kurkowski/tldextract#287]
Should IPv4 addresses with non-ASCII dots be accepted?

Example: `http://127\u30020\uff610\u002e1/foo/bar`

**Comment by john-kurkowski** [comment]
Interesting question! It's never come up. So I lean toward not? Are you encountering an issue?

On the other hand, implementing it wouldn't be a huge burden. It would be symmetrical with other dot-splitting code in the project.

**Comment by elliotwutingfeng** [comment]
Chrome and Firefox both automatically convert unicode dots to ascii dots for IPv4 addresses.

On a sidenote, for IPv6 addresses with a trailing IPv4 address, like `[aBcD:ef01:2345:6789:aBcD:ef01:127．0。0｡1]`, Chrome automatically converts the dots, but not Firefox.

**Comment by john-kurkowski** [comment]
Ok, I see the usability benefit. I'm open to a fix for this!
