### ISSUE TITLE
.co.nl TLD not parsed properly

### ISSUE THREAD

**Issue by dnissimi** [john-kurkowski/tldextract#291]
`>>> tldextract.extract('www.example.co.nl')`
`ExtractResult(subdomain='www.example', domain='co', suffix='nl')`

CO.NL. is the country code domain extension (ccTLD) for the Netherlands.

**Comment by john-kurkowski** [comment]
See [this FAQ entry](https://github.com/john-kurkowski/tldextract#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____) and [this explanation of public vs. private domains](https://github.com/john-kurkowski/tldextract/blob/3.4.0/README.md#public-vs-private-domains).

**Comment by dnissimi** [comment]
Thank you!
