### ISSUE TITLE
Use GitHub releases

### ISSUE THREAD

**Issue by john-kurkowski** [john-kurkowski/tldextract#301]
In [this commit](https://github.com/john-kurkowski/tldextract/commit/b3fe6563657957413b223ed33625a86b3b3a5bd5#commitcomment-118155718), @kloczek requested:

> Is it possible next time on release new version make the github release to have entry on https://github.com/john-kurkowski/tldextract/releases? 🤔 
>
> I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

**Comment by john-kurkowski** [comment]
The request sounds reasonable! I added a note to myself to my manual release steps. Next release and in releases going forward, I'll visit https://github.com/john-kurkowski/tldextract/releases/new. I'll probably copy into GitHub's text box whatever's in CHANGELOG.md for the 1 release. While GitHub's "Generate release notes" button is tempting, the project's CHANGELOG.md gives a little more structure that I think consumers are interested in. I'll leave this ticket open until I give the new process a try.

**Comment by kloczek** [comment]
Thank you 👍 😄

**Comment by john-kurkowski** [comment]
First GitHub release published. ✅

**Comment by kloczek** [comment]
Thank you very much👍 
Just found in logs that my automation was able correctly process email notification producing correctly building rpm packages with new version 😄
