### ISSUE TITLE
tldextract: incorrect resolution of www.nhs.uk

### ISSUE THREAD

**Issue by BigAlOne** [john-kurkowski/tldextract#302]
Hi

Could you please test the tldextract library with the following url:    www.nhs.uk

It returns ExtractResult(subdomain='', domain='www', suffix='nhs.uk'). And I dont believe this is correct.

Thanks
AA

**Comment by john-kurkowski** [comment]
Yup, @JanoutV called it. The behavior is correct. See also [the FAQ](https://github.com/john-kurkowski/tldextract/tree/3.4.4#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____).
