### ISSUE TITLE
Append cache with supplemented list

### ISSUE THREAD

**Issue by leeprevost** [john-kurkowski/tldextract#337]
@john-kurkowski is there a way to append my own (fairly short list) of registered domains that appear to be missing from the public suffix list for the segment I'm interested in?   For example, tldextract is not finding a response for:

Examples I would like to append to the local cache once refreshed.

k12.us.wa
s3.amazonaws.com
s3-us-west-2.amazonaws.com

**Comment by leeprevost** [comment]
Sorry, was looking at registered_domain property but see that tld does find these and correctly places them in suffix.   But, should I find examples that need to be appended, is that possible?

**Comment by elliotwutingfeng** [comment]
Would this (https://github.com/john-kurkowski/tldextract/blob/master/README.md#specifying-your-own-url-or-file-for-public-suffix-list-data) work for you?

I don't think appending custom rules to the default ruleset is supported, but you can make a copy of the public suffix list, modify it with your custom rules, and use that instead.

**Comment by leeprevost** [comment]
Yes, I think it would.  I need to determine where the public suffix list is downloaded from and how it needs to be processed with my rules.  I'll poke around in source and see if I can figure that out.

**Comment by john-kurkowski** [comment]
> I don't think appending custom rules to the default ruleset is supported, but you can make a copy of the public suffix list, modify it with your custom rules, and use that instead.

👍 This will work. Also, you can add a few, one-off suffixes with the `extra_suffixes` param, documented [a little further down in the README](https://github.com/john-kurkowski/tldextract/blob/5.1.2/README.md#can-you-add-suffix-____-can-you-make-an-exception-for-domain-____) and on the `TLDExtract` class.

> s3.amazonaws.com

That suffix at least is in the Public Suffix List already. See [this FAQ entry](https://github.com/john-kurkowski/tldextract/blob/5.1.2/README.md#public-vs-private-domains).

**Comment by leeprevost** [comment]
I believe the extra_suffixes param works for my use case.  I'll close this.
