### ISSUE TITLE
Python 3.2 compatibility

### ISSUE THREAD

**Issue by Agmagor** [john-kurkowski/tldextract#50]
Since Python 3, all strings are unicode so the u'...' notation do not make sense anymore.

One can't install your package on a Python 3 installation because of the return statement of this function

    def fetch_file(urls):
        """ Decode the first successfully fetched URL, from UTF-8 encoding to
        Python unicode.
        """
        s = ''

        for url in urls:
            try:
                conn = urlopen(url)
                s = conn.read()
            except Exception as e:
                LOG.error('Exception reading Public Suffix List url ' + url + ' - ' + str(e) + '.')
            else:
                return _decode_utf8(s)

        LOG.error('No Public Suffix List found. Consider using a mirror or constructing your TLDExtract with `fetch=False`.')
        return u''

**Comment by mauricioabreu** [comment]
It looks like this issue could be closed, no? Tests are running against a lot of Python versions. What is your opinion?

**Comment by hangtwenty** [comment]
I think @john-kurkowski 's [comment above](https://github.com/john-kurkowski/tldextract/issues/50#issuecomment-51098907) explained pretty well why 3.2 is annoying ... exactly to your point @mauricioabreu . 

But apparently we are almost there. See comment right above yours, @mauricioabreu : https://github.com/john-kurkowski/tldextract/issues/50#issuecomment-57949514

**Comment by mauricioabreu** [comment]
@hangtwenty ok, after reading it I think we lack of tests/coverage, right?

**Comment by hangtwenty** [comment]
@mauricioabreu  actually just fixing tests seemingly. Read https://github.com/john-kurkowski/tldextract/issues/50#issuecomment-57949514

**Comment by mauricioabreu** [comment]
@hangtwenty ok, I got it. Thanks!

**Comment by john-kurkowski** [comment]
Another option is to close this. No requestor activity in over a year. I'm not dead set on supporting old Python 3.x. 3.3-5 have far more users.

**Comment by hangtwenty** [comment]
I tried to use `pyenv` to install 3.2 and run tests, see where they fail, and maybe do the fix quickly. No dice:

```
mfloering at mfloering-mac in ~/Workspace/tldextract (master●)
$ nosetests
~/.pyenv/versions/3.2/lib/python3.2/site-packages/pkg_resources/__init__.py:103: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)

----------------------------------------------------------------------
Ran 0 tests in 0.013s

OK
```

So yeah @john-kurkowski given lack of requestor activity let's close this.
