### ISSUE TITLE
uk.com and us.com?

### ISSUE THREAD

**Issue by cccc1999** [john-kurkowski/tldextract#59]
correct me if im wrong but it seems that a uk.com and us.com are top level domains as well?

**Comment by kristjanr** [comment]
Dear John,
I cannot get it working with Python3.4
Should this work correctly with Python3.4 also? What am I doing wrong?
![screenshot 2015-03-05 10 59 48](https://cloud.githubusercontent.com/assets/1203138/6501922/0448d094-c327-11e4-9c5f-754ca65bf160.png)

**Comment by kristjanr** [comment]
OK, it works on Python3.3, but not on Python3.4:
 
Python 3.3.6 (default, Feb 26 2015, 04:21:55) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tldextract import TLDExtract
>>> ex = TLDExtract(include_psl_private_domains=True)
>>> ex('http://www.cscs.uk.com/')
ExtractResult(subdomain='www', domain='cscs', suffix='uk.com')

**Comment by kristjanr** [comment]
I updated to Python3.4.3 and it works fine:

Python 3.4.3 (default, Feb 27 2015, 00:22:26) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tldextract import TLDExtract
>>> ex = TLDExtract(include_psl_private_domains=True)
>>> ex('http://www.cscs.uk.com/')
ExtractResult(subdomain='www', domain='cscs', suffix='uk.com')

**Comment by kristjanr** [comment]
We cannot yet update to Python 3.4.3, so made our own fix:
Just commented out the part about logging:
        if LOG.isEnabledFor(logging.DEBUG):
            import difflib
            with closing(pkg_resources.resource_stream(__name__, '.tld_set_snapshot')) as snapshot_file:
                snapshot = sorted(pickle.load(snapshot_file))
            new = sorted(tlds)
            for line in difflib.unified_diff(snapshot, new, fromfile=".tld_set_snapshot", tofile=self.cache_file):
                if sys.version_info < (3,):
                    sys.stderr.write(line.encode('utf-8') + "\n")
                else:
                    sys.stderr.write(line + "\n")

**Comment by john-kurkowski** [comment]
Any idea what the logging has to do with your issue?

Do you just need to update your cache file? Is this related to your #64?

**Comment by kristjanr** [comment]
Yes you are right. I only needed to update the cache file. Yes, related to #64
