### ISSUE TITLE
stderr spam, debug output to info enabled by default?

### ISSUE THREAD

**Issue by Granitas** [john-kurkowski/tldextract#63]
Hi,
it seems that stderr output debug logging is enabled by default? I have a scrapy project that uses tldextract once and upon import it seems to spam the log with 2000 debug lines. starts with:
```
[tldextract] computed TLDs: [chikuho.fukuoka.jp, భారత్, 公司.hk, pvt.ge, matsuzaki.shizuoka.jp, name.eg, tsuruga.fukui.jp, in-addr.arpa, hisayama.fukuoka.jp, name.et, ...]
[stderr] --- .tld_set_snapshot
```
 How I fixed it is:
```
#disable tldextract stderr spam
logger = logging.getLogger('tldextract')
logger.setLevel('WARNING')
```

If this is not enabled by default could it be that Tldextract grabs some other loggers level by default ? I'm not too familiar with logging module so I'm not sure what's the cause of this however spaming stderr upon import is something that shouldn't happen.

**Comment by john-kurkowski** [comment]
tldextract doesn't set a default log level. It leaves it to client applications to configure their logging. If you set your app to debug, you'll get tldextract debug logging.

```python
>>> from tldextract.tldextract import LOG
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> LOG.debug('spam spam spam')
DEBUG:tldextract:spam spam spam
>>> LOG.error('error error error')
ERROR:tldextract:error error error
```

Contrast with a higher level:

```python
>>> from tldextract.tldextract import LOG
>>> import logging
>>> logging.basicConfig(level=logging.WARN)
>>> LOG.debug('spam spam spam')
>>>
```

If you don't configure logging, you won't see anything from tldextract (Python will give a one-time error that you haven't configured logging though).

```python
>>> from tldextract.tldextract import LOG
>>> LOG.error('help, someone log this!')
No handlers could be found for logger "tldextract"
>>> LOG.error('is anybody there?')
>>>
```

So is your app set to permit debug logging? If so, you did the right thing to selectively turn off tldextract's debug logging.

**Comment by john-kurkowski** [comment]
To your point, although it's controlled by the debug logging level, I don't see a good reason why I ultimately write the diff to stderr.

**Comment by john-kurkowski** [comment]
Removed the out-of-the-blue stderr.

Is there anything else here?

**Comment by Granitas** [comment]
Nope, the log seems to be nice and clean now!

Cheers!
