### ISSUE TITLE
tldextract --update does not download private domains

### ISSUE THREAD

**Issue by kristjanr** [john-kurkowski/tldextract#64]
If I run tldextract --update to update domains file then, because of this line https://github.com/john-kurkowski/tldextract/blob/1.5.1/tldextract/tldextract.py#L264 the private domains are not downloaded.
Therefore, if later I create TLDExtract(include_psl_private_domains=True) class, the private domains are not mapped.
I recommend always downloading the full list and replace line 264 as 
TLD_EXTRACTOR = TLDExtract(include_psl_private_domains=True)

**Comment by kristjanr** [comment]
I realized later on that this behavior is intentional. And that my pull request is no good...

**Comment by john-kurkowski** [comment]
With #65, now it _can_ include private domains. You must opt into it.

Separately filed #66 for the ideal fix, which always stores private domains but only includes them in results when the user asks for them.
