### ISSUE TITLE
Public/private results depend on how cache file was persisted

### ISSUE THREAD

**Issue by john-kurkowski** [john-kurkowski/tldextract#66]
**Repro**
1. `TLDExtract(include_psl_private_domains=True).update()`
2. `TLDExtract(include_psl_private_domains=False).extract('foo.appspot.com')`

**Expected:** foo appspot com
**Actual:** foo.appspot com

The opposite order is also broken.

Related to #64.

**Comment by john-kurkowski** [comment]
I think the cache should always contain both public/private, and then results are filtered at runtime.

**Comment by mauricioabreu** [comment]
I agree with what you said above. Cache should contain everything. It is light and makes the codebase easier to handle.

**Comment by wumpus** [comment]
With the current situation, all users of tldextract in a given container/pyenv/whatever have to agree whether they want public or public+private. Imagine the fun if module A and module B disagree...

**Comment by a1Gupta** [comment]
Did anyone find solution for this ? @john-kurkowski Are you working on it ? I want to use both options for include_psl_private_domains in different modules.

**Comment by john-kurkowski** [comment]
Nope, I don't think anybody's worked on it.

**Comment by brycedrennan** [comment]
This is now addressed in https://github.com/john-kurkowski/tldextract/pull/144

**Comment by john-kurkowski** [comment]
Closed via #207.
