### ISSUE TITLE
using in GAE

### ISSUE THREAD

**Issue by dusking** [john-kurkowski/tldextract#68]
Hi,
thanks for the lib, works great!
but I want to use it in my GAE server, 
is there a nice way to load the tld cache file not by reading the file, since there is no real path to it..?
Thanks!

**Comment by dusking** [comment]
found the way to read files from gae - read them relative to the root...
question not relevant for this lib... :)

**Comment by mdagcilar** [comment]
Hi could you elaborate on your answer please? 

Where exactly did you have to change the relative paths to root?
