### ISSUE TITLE
_asdict on ExtractResult empty on Python 3+

### ISSUE THREAD

**Issue by otakucode** [john-kurkowski/tldextract#70]
When using tldextract on Python 3.4 I noticed that the __dict__ attribute of the namedtuple ExtractResult would always be empty, which caused its _asdict method to also return an empty dict.  This is because ExtractResult does not define a __slots__ member, which prevents the parent classes dict from being added.  I am not sure which version of Python changed this behavior.  I added a unit test (and also added Py34 to the tox.ini environments) for this issue and it passed for Python 2.7, but failed for Python 3.4.  Those are the only versions I had installed.  I fixed the issue in tldextract.py and all tests now pass, both in 2.7 and 3.4.  I created pull request #69 with the fix and additional test.

**Comment by john-kurkowski** [comment]
Merged #69. Thanks!

**Comment by john-kurkowski** [comment]
For posterity, this was a bug in Python, somewhere in the 3.4.x series. The PR's workaround is no longer necessary at least as of Python 3.5.2. See [this SO discussion](https://stackoverflow.com/questions/40677747/asdict-in-python-3-namedtuple-subclass-returns-empty-dictionary).
