### ISSUE TITLE
UnicodeEncodeErrors on logging

### ISSUE THREAD

**Issue by arski** [john-kurkowski/tldextract#84]
File "/www/sites/virtualenv/lib/python3.4/site-packages/tldextract/tldextract.py", line 267, in _get_tld_extractor
        self._cache_tlds(tlds)
    File "/www/sites/virtualenv/lib/python3.4/site-packages/tldextract/tldextract.py", line 308, in _cache_tlds
        LOG.info("computed TLDs: [%s, ...]", ', '.join(list(tlds)[:10]))

Is throwing me a bunch of UnicodeEncodeErrors on the latest pip version.. any idea what that is all about?

Thanks!

**Comment by john-kurkowski** [comment]
Hmm. And older versions are fine? It doesn't ring a bell. 

Perhaps the test coverage on that `LOG.info` code path is weak. It's not the first time it's done something like this. Adding a test for it should reveal the issue and stop it repeatedly coming up.

**Comment by arski** [comment]
haven't tested older versions, sorry my comment seemed to imply it, I was just stating what version I'm on for some reason :)

I'm running tldextract inside Django if that's of any value, but still the error must be originating from here. Very odd too since I checked the data that was passed to tldextract is completely plain, just alphanums and dots :(

**Comment by hangtwenty** [comment]
Some suggestions for whoever takes a stab at fixing ... ( @arski wanna try?) --

* Ensure it's a unicode string like `u"string"` that we're passing to `LOG.info`
* Switch the code from using `%s` to preferred way these days ... like ` u"string {} ".format(blah)`
* Additionally, wrap the statement in a `log.isEnabledFor(<level>)` ... where in this case `<level>` would b `logging.INFO`

**Comment by hangtwenty** [comment]
On second thought the log statement could also be updated such that it doesn't interpolate any TLDs. It doesn't really need to ... It interpolates only 10 of them which is a very small fraction of them. So why not just `LOG.info("computed tlds")` or  `LOG.debug("computed tlds")`

**Comment by arski** [comment]
Hey, I'm not sure if isEnabledFor calls are really necessary - that's the job of the logger output config to filter out messages from uninteresting levels.

But I very much agree with your second comment - I was going to suggest that and now that you say it, it seems like the best solution :) Do you want a PR for that? Being a one-line change with nothing to test I imagine you don't really, right? :) Thanks!

**Comment by john-kurkowski** [comment]
You're right, `isEnabledFor` would only be to protect against unnecessary string building.

1 line PRs welcome! If we simplify to not interpolate anything, there's nothing we absolutely must test I suppose.

Although it feels like we aren't exercising this code path in the test suite. Which bothers me.

**Comment by john-kurkowski** [comment]
No more interpolations thanks to #85.

**Comment by john-kurkowski** [comment]
(Quelled my test coverage worry with 8bad5032de34befab478b8098c5f12b15621d56e. It was covered but I've made the test more explicit. Not sure why it didn't trigger the OP's issue. But since that issue is no longer possible anyway: meh.)
