### ISSUE TITLE
UnicodeDecodeError when parsing public suffix list

### ISSUE THREAD

**Issue by alexlatchford** [john-kurkowski/tldextract#87]
Getting this error, looks like it's being caused by a recent update to the public suffix list at https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat

```
alexlatchford@Alexs-MacBook-Air a8_nlp_tools (master) $ tldextract --version
tldextract 1.7.4
alexlatchford@Alexs-MacBook-Air a8_nlp_tools (master) $ tldextract http://forums.bbc.co.uk
Traceback (most recent call last):
  File "/usr/local/bin/tldextract", line 9, in <module>
    load_entry_point('tldextract==1.7.4', 'console_scripts', 'tldextract')()
  File "/Library/Python/2.7/site-packages/tldextract/tldextract.py", line 470, in main
    print(' '.join(extract(i))) # pylint: disable=superfluous-parens
  File "/Library/Python/2.7/site-packages/tldextract/tldextract.py", line 343, in extract
    return TLD_EXTRACTOR(url)
  File "/Library/Python/2.7/site-packages/tldextract/tldextract.py", line 214, in __call__
    suffix_index = self._get_tld_extractor().suffix_index(translations)
  File "/Library/Python/2.7/site-packages/tldextract/tldextract.py", line 254, in _get_tld_extractor
    raw_suffix_list_data = fetch_file(self.suffix_list_urls)
  File "/Library/Python/2.7/site-packages/tldextract/tldextract.py", line 375, in fetch_file
    return _decode_utf8(text)
  File "/Library/Python/2.7/site-packages/tldextract/tldextract.py", line 389, in _decode_utf8
    return unicode(text, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Can't seem to do any URLs at all at the moment because the cache isn't loaded :(

**Comment by john-kurkowski** [comment]
I coincidentally ran CI at the same time as you and saw this too. However the problem has [since gone away](https://travis-ci.org/john-kurkowski/tldextract/builds/98941578).

**Comment by john-kurkowski** [comment]
Let's leave this open though. I'd welcome a PR to trap the error. If the library can't decode UTF-8 from the response, it should warn but fall back to its included snapshot.

**Comment by alexlatchford** [comment]
Yeah I was debugging it and was trying different commit versions of the suffix_list.dat and magically it just started working again so didn't manage to actually find the issue. I was thinking potentially a utf-16 chars being issue but everything they've added to the file within the last month or so is utf-8 compatible so didn't pinpoint anything.

**Comment by jnozsc** [comment]
I meet this issue today and I would like to contribute a pull request. before I create the pull request, may I have the method about how to run the unit test locally?

**Comment by jnozsc** [comment]
I just create a pull request, which suppose to handle the gzip response

**Comment by john-kurkowski** [comment]
> may I have the method about how to run the unit test locally?

It's [here in the README](https://github.com/john-kurkowski/tldextract#running-the-test-suite).
