### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by mcrotti** [john-kurkowski/tldextract#9]
This is a non blocking error that I can capture only if I import logging module.

manuel@Manuel-NG:~>python
Python 2.7.2 (default, Oct  4 2011, 14:55:10) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
...

> > > import tldextract
> > > import logging
> > > logging.basicConfig()
> > > one, two, three = tldextract.extract('forums.bbc.co.uk/nano/micro.html')

ERROR:/Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg/tldextract/tldextract.pyc:error reading TLD cache file /Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg/tldextract/.tld_set: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg/tldextract/.tld_set'
WARNING:/Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg/tldextract/tldextract.pyc:unable to cache TLDs in file /Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg/tldextract/.tld_set: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg/tldextract/.tld_set'

touch'ed and chown'ed .tls_set with no success

chown'ed the folder, everything worked fine. Something to review in the install process, under OSX? (mine is Lion 10.7.3)

**Comment by c24b** [comment]
+1 Up!

**Comment by c24b** [comment]
The only way for now to silent this WARNING is 
logging.getLogger("tldextract").setLevel(logging.CRITICAL)
but it really should be a cache not tmp file that requires to change permission of the file were the packages is install so in prod in multiple places will be non very handy

**Comment by sharmaeshaan** [comment]
You need to do a `sudo chown -R username:group directory` to change the permissions/ownership of the `/Library/Python/2.7/site-packages/tldextract-1.0-py2.7.egg` folder to allow the program to read/write files.

**Comment by iMerica** [comment]
This caching feature is nice in theory, but its a bit much to expect a 3rd party python package to have write access to the file system. Anyone running this in a Docker container will see this error/running by default. 

Please consider making caching disabled by default or support for caching capability using more appropriate tools like Memcache or Redis.

**Comment by john-kurkowski** [comment]
Good explanation! 

Trying to understand better. Are people bothered by the verbosity? Or that this library is trying to write at all? 

Remember, this is a _warning_ and the library will continue with full operation and up-to-date definitions. I thought the warning brought attention that something is misconfigured, and you're relying on a live HTTP request on every application startup. If you're good with that, it's easy to silence. See [this FAQ entry](https://github.com/john-kurkowski/tldextract/tree/2.2.2#note-about-caching).

**Comment by lifenautjoe** [comment]
> Good explanation!
> 
> Trying to understand better. Are people bothered by the verbosity? Or that this library is trying to write at all?
> 
> Remember, this is a _warning_ and the library will continue with full operation and up-to-date definitions. I thought the warning brought attention that something is misconfigured, and you're relying on a live HTTP request on every application startup. If you're good with that, it's easy to silence. See [this FAQ entry](https://github.com/john-kurkowski/tldextract/tree/2.2.2#note-about-caching).

Its not a warning over here. The request fails entirely with 

```
error
[Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/tldextract/.suffix_cache'
```

Perhaps good to let people know where the file was downloaded and for them to copy it to their repository somewhere in the top parts of the README ?

**Comment by john-kurkowski** [comment]
> Its not a warning over here.

That's a bug, #209. Try [3.0.2](https://github.com/john-kurkowski/tldextract/releases/tag/3.0.2). That should restore the former behavior.
