### ISSUE TITLE
tld .br.com problem

### ISSUE THREAD

**Issue by humrochagf** [john-kurkowski/tldextract#90]
when i try to extract the tld mysite.br.com it handles br as the domain instead of part of the sufix.

this is a error at the lib or there is a way to say that the .br.com is a suffix?

**Comment by john-kurkowski** [comment]
The PSL considers [br.com](https://github.com/publicsuffix/list/blob/73668f743df8125477d38690807e3a9a1e1e9f19/public_suffix_list.dat#L10657) a private domain. Notice the ["BEGIN PRIVATE DOMAINS"](https://github.com/publicsuffix/list/blob/73668f743df8125477d38690807e3a9a1e1e9f19/public_suffix_list.dat#L10594) a few lines up.

If you want to include private domains when using tldextract, or use a custom PSL, see [the docs for constructing a `TLDExtract` instance](https://github.com/john-kurkowski/tldextract/blob/1.7.5/tldextract/tldextract.py#L127-L157).

**Comment by humrochagf** [comment]
got it!

Thanks alot
